In [1]:
from chython import smarts, smiles
import pandas as pd
from synplan.utils.visualisation import get_route_svg_from_json
from route_analysis.alchemical_rules.unwrap_alchemical import unwrap_alchemical_rule
from IPython.display import display, SVG
from route_analysis.composite_rules.unwrap import split_composite_rule, unwrap_composite_rule

In [5]:
label= 'n1'

In [6]:
import json

routes_path = f"../data/{label}-routes.json"

with open(routes_path) as f:
    routes = json.load(f)

# PaRoutes file is a list, while get_route_svg_from_json expects route_id lookup.
routes_json = {i: route for i, route in enumerate(routes)}

In [7]:
# alchemy_rules_path = '../alchemical_out/n1/n1_alchemical_rules.tsv'

# alchemy_rules_path = '../resu_alchem/n1/n1_alchemical_rules.tsv'
# alchemy_rules_path = '../resu_alchem/n5/n5_alchemical_rules.tsv'
# alchemy_rules_path = '../resu_alchem/all/all_alchemical_rules.tsv'

alchemy_rules_path = f'../resu_alchem/{label}/{label}_alchemical_rules.tsv'

df = pd.read_csv(alchemy_rules_path, sep='\t')
df

FileNotFoundError: [Errno 2] No such file or directory: '../resu_alchem/n1/n1_alchemical_rules.tsv'

In [26]:
x = 8
df.iloc[x]

Alchemical_rule          [C;D3:1]-[C;D2:2]=[O;D1:3]>>[C;D3:1]-[C;D3:2](...
output_reactants_num                                                     1
popularity                                                              59
route_ids_size                                                          59
Reference                69,123,167,210,305,345,428,534,585,592,615,893...
Target_molecules         C/C(=C(\F)C=O)c1cc2c(c(Br)c1OC(C)C)C(C)(C)CC=C...
composite_rules_size                                                    28
Composite_rule_sizes                                                   2,3
Composite_rules          [C:1](:[C;D3:2]-[C;D2:3]=[O;D1:4]):[N:5]>>[C:1...
Source_composite_rows    n5_t2_composite_rules.tsv:100,n5_t2_composite_...
pseudo_reactions_size                                                   52
Pseudo_reaction_ids      p306,p307,p308,p309,p310,p311,p312,p313,p314,p...
Name: 8, dtype: object

In [27]:
alchemical_rule = smarts(df.iloc[x]['Alchemical_rule'])
alchemical_rule

In [13]:
comp_rules = df.iloc[x]['Composite_rules'].split(' || ')
for comp_rule in comp_rules:
    rules = comp_rule.split('$')
    for rule in rules:
        display(smarts(rule))
    print(comp_rule)

[C:1]#[C:2]-[C;D2:3]-[N;D2:4]-[C;D3:5](=[O;D1:6])-[C;D3:7]>>[C;D3:5](=[O;D1:6])(-[C;D3:7])-[O;D1:8].[C:1]#[C:2]-[C;D2:3]-[N;D1:4]$[C:1]-[C;D3:2](=[O:3])-[O;D1:4]>>[C:1]-[C;D3:2](=[O:3])-[O;D2:4]-[C;D1:5]

[C:1]:1:[N:2]:[O:3]:[C:4]:[C;D3:5]:1-[C;D3:6](=[O;D1:7])-[N;D2:8]-[C;D2:9]>>[C:1]:1:[N:2]:[O:3]:[C:4]:[C;D3:5]:1-[C;D3:6](=[O;D1:7])-[O;D1:10].[N;D1:8]-[C;D2:9]$[C:1]-[C;D3:2](=[O:3])-[O;D1:4]>>[C:1]-[C;D3:2](=[O:3])-[O;D2:4]-[C;D1:5]

[C:1]:[C;D3:2](-[C;D3:3](=[O;D1:4])-[N;D2:5]-[C;D2:6]):[N:7]>>[C:1]:[C;D3:2](-[C;D3:3](=[O;D1:4])-[O;D1:8]):[N:7].[N;D1:5]-[C;D2:6]$[C:1]-[C;D3:2](=[O:3])-[O;D1:4]>>[C:1]-[C;D3:2](=[O:3])-[O;D2:4]-[C;D1:5]

[C:1]:[C;D3:2](-[C;D3:3](=[O;D1:4])-[N;D2:5]-[C;D2:6]):[S:7]>>[C:1]:[C;D3:2](-[C;D3:3](=[O;D1:4])-[O;D1:8]):[S:7].[N;D1:5]-[C;D2:6]$[C:1]-[C;D3:2](=[O:3])-[O;D1:4]>>[C:1]-[C;D3:2](=[O:3])-[O;D2:4]-[C;D1:5]

[C:1]:[C;D3:3](:[N:2])-[C;D3:4](=[O;D1:5])-[N;D2:6]-[C;D2:7]>>[C:1]:[C;D3:3](:[N:2])-[C;D3:4](=[O;D1:5])-[O;D1:8].[N;D1:6]-[C;D2:7]$[C:1]-[C;D3:2](=[O:3])-[O;D1:4]>>[C:1]-[C;D3:2](=[O:3])-[O;D2:4]-[C;D1:5]

[C;D2:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[C;D3:5](:[C:6]):[N:7]>>[C;D3:3](=[O;D1:4])(-[C;D3:5](:[C:6]):[N:7])-[O;D1:8].[C;D2:1]-[N;D1:2]$[C:1]-[C;D3:2](=[O:3])-[O;D1:4]>>[C:1]-[C;D3:2](=[O:3])-[O;D2:4]-[C;D1:5]

[C;D2:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[C;D3:5](:[C:6]):[S:7]>>[C;D3:3](=[O;D1:4])(-[C;D3:5](:[C:6]):[S:7])-[O;D1:8].[C;D2:1]-[N;D1:2]$[C:1]-[C;D3:2](=[O:3])-[O;D1:4]>>[C:1]-[C;D3:2](=[O:3])-[O;D2:4]-[C;D1:5]

[C;D2:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[C;D3:5](:[N:6]):[C:7]>>[C;D3:3](=[O;D1:4])(-[C;D3:5](:[N:6]):[C:7])-[O;D1:8].[C;D2:1]-[N;D1:2]$[O:1]=[C;D3:2](-[O;D1:3])-[C:4]>>[O:1]=[C;D3:2](-[O;D2:3]-[C;D1:5])-[C:4]

[C;D2:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[C;D3:5]:[C:6]:[N:7]>>[C;D3:3](=[O;D1:4])(-[C;D3:5]:[C:6]:[N:7])-[O;D1:8].[C;D2:1]-[N;D1:2]$[C:1]-[C;D3:2](=[O:3])-[O;D1:4]>>[C:1]-[C;D3:2](=[O:3])-[O;D2:4]-[C;D1:5]

[C;D2:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[C;D3:5]:[C:6]:[N:7]>>[C;D3:3](=[O;D1:4])(-[C;D3:5]:[C:6]:[N:7])-[O;D1:8].[C;D2:1]-[N;D1:2]$[O:1]=[C;D3:2](-[O;D1:3])-[C:4]>>[O:1]=[C;D3:2](-[O;D2:3]-[C;D1:5])-[C:4]

[C;D2:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[C;D3:5]>>[C;D3:3](=[O;D1:4])(-[C;D3:5])-[Cl;D1:6].[C;D2:1]-[N;D1:2]$[C;D3:1]-[C;D3:2](=[O;D1:3])-[Cl;D1:4]>>[Cl;D1:4]-[C;D3:8](-[C;D3:6](=[O:5])-[Cl:7])=[O;D1:9].[C;D3:1]-[C;D3:2](=[O;D1:3])-[O;D1:10]$[C:1]-[C;D3:2](=[O:3])-[O;D1:4]>>[C:1]-[C;D3:2](=[O:3])-[O;D2:4]-[C;D1:5]

[C;D2:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[C;D3:5]>>[C;D3:3](=[O;D1:4])(-[C;D3:5])-[Cl;D1:6].[C;D2:1]-[N;D1:2]$[C;D3:1]-[C;D3:2](=[O;D1:3])-[Cl;D1:4]>>[Cl;D1:4]-[S;D3:6](=[O;D1:5])-[Cl;D1:7].[C;D3:1]-[C;D3:2](=[O;D1:3])-[O;D1:8]$[C:1]-[C;D3:2](=[O:3])-[O;D1:4]>>[C:1]-[C;D3:2](=[O:3])-[O;D2:4]-[C;D1:5]

[C;D2:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[C;D3:5]>>[C;D3:3](=[O;D1:4])(-[C;D3:5])-[Cl;D1:6].[C;D2:1]-[N;D1:2]$[O;D1:1]=[C;D3:2](-[Cl;D1:3])-[C;D3:4]>>[Cl;D1:3]-[C;D3:8](-[C;D3:6](=[O:5])-[Cl:7])=[O;D1:9].[O;D1:1]=[C;D3:2](-[C;D3:4])-[O;D1:10]$[O:1]=[C;D3:2](-[O;D1:3])-[C:4]>>[O:1]=[C;D3:2](-[O;D2:3]-[C;D1:5])-[C:4]

[C;D2:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[C;D3:5]>>[C;D3:3](=[O;D1:4])(-[C;D3:5])-[O;D1:6].[C;D2:1]-[N;D1:2]$[C:1]-[C;D3:2](=[O:3])-[O;D1:4]>>[C:1]-[C;D3:2](=[O:3])-[O;D2:4]-[C;D1:5]

[C;D2:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[C;D3:5]>>[C;D3:3](=[O;D1:4])(-[C;D3:5])-[O;D1:6].[C;D2:1]-[N;D1:2]$[O:1]=[C;D3:2](-[O;D1:3])-[C:4]>>[O:1]=[C;D3:2](-[O;D2:3]-[C;D1:5])-[C:4]

[C;D3:1](-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D2:5]):[C:6]:[N:7]>>[C;D3:1](-[C;D3:2](=[O;D1:3])-[O;D1:8]):[C:6]:[N:7].[N;D1:4]-[C;D2:5]$[C:1]-[C;D3:2](=[O:3])-[O;D1:4]>>[C:1]-[C;D3:2](=[O:3])-[O;D2:4]-[C;D1:5]

[C;D3:1]-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D2:5]>>[C;D3:1]-[C;D3:2](=[O;D1:3])-[Cl;D1:6].[N;D1:4]-[C;D2:5]$[C;D3:1]-[C;D3:2](=[O;D1:3])-[Cl;D1:4]>>[Cl;D1:4]-[C;D3:8](-[C;D3:6](=[O:5])-[Cl:7])=[O;D1:9].[C;D3:1]-[C;D3:2](=[O;D1:3])-[O;D1:10]$[C:1]-[C;D3:2](=[O:3])-[O;D1:4]>>[C:1]-[C;D3:2](=[O:3])-[O;D2:4]-[C;D1:5]

[C;D3:1]-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D2:5]>>[C;D3:1]-[C;D3:2](=[O;D1:3])-[O;D1:6].[N;D1:4]-[C;D2:5]$[C:1]-[C;D3:2](=[O:3])-[O;D1:4]>>[C:1]-[C;D3:2](=[O:3])-[O;D2:4]-[C;D1:5]

[C;D3:1]-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D2:5]>>[C;D3:1]-[C;D3:2](=[O;D1:3])-[O;D2:13]-[N;D3:12]-1-[C:7](=[O:6])-[C:8]-[C:9]-[C:10]-1=[O:11].[N;D1:4]-[C;D2:5]$[C;D3:1]-[C;D3:2](=[O;D1:3])-[O;D2:4]-[N;D3:5]-1-[C:6](=[O:7])-[C:8]-[C:9]-[C:10]-1=[O:11]>>[O;D2:4](-[N;D3:5]-1-[C:6](=[O:7])-[C:8]-[C:9]-[C:10]-1=[O:11])-[C;D3:15](-[N;D3:13](-[C:12])-[C:14])=[N;D3+:16](-[C:17])-[C:18].[C;D3:1]-[C;D3:2](=[O;D1:3])-[O;D1:19]$[C:1]-[C;D3:2](=[O:3])-[O;D1:4]>>[C:1]-[C;D3:2](=[O:3])-[O;D2:4]-[C;D1:5]

[N:1]-[C:2](=[O:3])-[C;D2:4]-[N;D2:5]-[C;D3:6](=[O;D1:7])-[C;D3:8](:[C:9]):[S:10]>>[C;D3:6](=[O;D1:7])(-[C;D3:8](:[C:9]):[S:10])-[O;D1:11].[N:1]-[C:2](=[O:3])-[C;D2:4]-[N;D1:5]$[O:1]=[C;D3:2](-[O;D1:3])-[C:4]>>[O:1]=[C;D3:2](-[O;D2:3]-[C;D1:5])-[C:4]

[N:1]:[C:2]:[C;D3:3](-[C;D3:4](=[O;D1:5])-[N;D2:6]-[C;D2:7]):[N:8]>>[N:1]:[C:2]:[C;D3:3](-[C;D3:4](=[O;D1:5])-[O;D1:9]):[N:8].[N;D1:6]-[C;D2:7]$[C:1]-[C;D3:2](=[O:3])-[O;D1:4]>>[C:1]-[C;D3:2](=[O:3])-[O;D2:4]-[C;D1:5]

[N:1]:[C:2]:[C;D3:3]-[C;D3:4](=[O;D1:5])-[N;D2:6]-[C;D2:7]>>[N:1]:[C:2]:[C;D3:3]-[C;D3:4](=[O;D1:5])-[O;D1:8].[N;D1:6]-[C;D2:7]$[C:1]-[C;D3:2](=[O:3])-[O;D1:4]>>[C:1]-[C;D3:2](=[O:3])-[O;D2:4]-[C;D1:5]

[O:1]-[C:2](=[O:3])-[C;D2:4]-[N;D2:5]-[C;D3:6](=[O;D1:7])-[C;D3:8](:[C:9]):[N:10]>>[C;D3:6](=[O;D1:7])(-[C;D3:8](:[C:9]):[N:10])-[O;D1:11].[O:1]-[C:2](=[O:3])-[C;D2:4]-[N;D1:5]$[C:1]-[C;D3:2](=[O:3])-[O;D1:4]>>[C:1]-[C;D3:2](=[O:3])-[O;D2:4]-[C;D1:5]

[O:1]-[C:2](=[O:3])-[C;D2:4]-[N;D2:5]-[C;D3:6](=[O;D1:7])-[C;D3:8]:[C:9]:[N:10]>>[C;D3:6](=[O;D1:7])(-[C;D3:8]:[C:9]:[N:10])-[O;D1:11].[O:1]-[C:2](=[O:3])-[C;D2:4]-[N;D1:5]$[C:1]-[C;D3:2](=[O:3])-[O;D1:4]>>[C:1]-[C;D3:2](=[O:3])-[O;D2:4]-[C;D1:5]

[O:1]-[C:2](=[O:3])-[C;D2:4]-[N;D2:5]-[C;D3:6](=[O;D1:7])-[C;D3:8]>>[C;D3:6](=[O;D1:7])(-[C;D3:8])-[O;D1:9].[O:1]-[C:2](=[O:3])-[C;D2:4]-[N;D1:5]$[C:1]-[C;D3:2](=[O:3])-[O;D1:4]>>[C:1]-[C;D3:2](=[O:3])-[O;D2:4]-[C;D1:5]

[O;D1:1]=[C;D3:2](-[N;D2:3]-[C;D2:4])-[C;D3:5]>>[O;D1:1]=[C;D3:2](-[C;D3:5])-[O;D1:6].[N;D1:3]-[C;D2:4]$[O:1]=[C;D3:2](-[O;D1:3])-[C:4]>>[O:1]=[C;D3:2](-[O;D2:3]-[C;D1:5])-[C:4]

In [17]:
mols = df.iloc[x]['Target_molecules'].split(',')

In [18]:
t_mol = mols[1]
display(smiles(t_mol))
t_mol

'CC(C)(C)[Si](OCc1cccc(CC#N)c1)(c1ccccc1)c1ccccc1'

In [22]:
str(alchemical_rule)

'[C;D3:1]-[C;D2:2]-[C;D2:3]#[N;D1:4]>>[C;D1:3]#[N;D1:4].[C;D3:1]-[C;D2:2]-[O;D1:5]'

In [23]:
part_route = unwrap_alchemical_rule(t_mol, str(alchemical_rule))
part_route

{0: {'type': 'mol',
  'smiles': 'c1ccccc1[Si](c2ccccc2)(C(C)(C)C)OCc3cc(CC#N)ccc3',
  'in_stock': False,
  'children': [{'type': 'reaction',
    'smiles': '[cH:18]1[cH:19][cH:20][cH:21][cH:22][c:17]1[Si:5]([c:23]2[cH:24][cH:25][cH:26][cH:27][cH:28]2)([C:2]([CH3:1])([CH3:3])[CH3:4])[O:6][CH2:7][c:8]3[cH:16][c:12]([CH2:13][C:14]#[N:15])[cH:11][cH:10][cH:9]3>>[N:15]#[CH:14].[cH:18]1[cH:19][cH:20][cH:21][cH:22][c:17]1[Si:5]([c:23]2[cH:24][cH:25][cH:26][cH:27][cH:28]2)([C:2]([CH3:1])([CH3:3])[CH3:4])[O:6][CH2:7][c:8]3[cH:9][cH:10][cH:11][c:12]([CH2:13][OH:29])[cH:16]3',
    'rule_key': 'alchemical:1',
    'children': [{'type': 'mol',
      'smiles': 'c1ccccc1[Si](c2ccccc2)(C(C)(C)C)OCc3cccc(CO)c3',
      'in_stock': True},
     {'type': 'mol', 'smiles': 'N#C', 'in_stock': True}]}]}}

In [24]:
display(SVG(get_route_svg_from_json(part_route, 0)))

In [19]:
route_id = int(df.iloc[x]['Reference'].split(',')[0])
route_id

264

In [18]:
svg = get_route_svg_from_json(routes_json, route_id, labeled=True)
display(SVG(svg))

In [33]:
new_df = df[df["Composite_rule_sizes"].astype(str).str.contains(",", na=False)]
new_df.shape

(177, 12)

In [34]:
s = df["Composite_rule_sizes"].astype(str).str.strip()

# rows with multiple values, e.g. "2,3"
is_mixed = s.str.contains(",", na=False)

# counts for single values only
single_counts = s[~is_mixed].value_counts().sort_index()

# add mixed count
stats = pd.concat([
    single_counts,
    pd.Series({"mixed": is_mixed.sum()})
])

stats

2        8570
3        2643
4         650
5         133
mixed     177
dtype: int64

In [35]:
combo_stats = s.value_counts().sort_index().reset_index()
combo_stats.columns = ["Composite_rule_sizes", "count"]
combo_stats

  Composite_rule_sizes  count
0                    2   8570
1                  2,3    145
2                2,3,4      6
3                  2,4     10
4                    3   2643
5                  3,4     15
6                    4    650
7                  4,5      1
8                    5    133

In [25]:
val = "4"

rows_with_val = df[
    df["Composite_rule_sizes"]
    .astype(str)
    .str.split(",")
    .apply(lambda xs: val in [x.strip() for x in xs])
]
rows_with_val

,Alchemical_rule,popularity,route_ids_size,Reference,Target_molecules,composite_rules_size,Composite_rule_sizes,Composite_rules,Source_composite_rows,pseudo_reactions_size,Pseudo_reaction_ids,Alchemical_cgr
589,[C:1]:[C;D3:2](-[C;D3:3](=[N;D1:4])-[N;D2:5]-[...,2,2,"1621,2578","Cc1cc(C(=N)NO)nc(Cl)n1,Cc1cc(C(=N)NO)nc(NC(C)C)n1",2,"3,4",[C:1]:[C;D3:2](-[C;D3:3](=[N;D1:4])-[N;D2:5]-[...,"n1_t3_composite_rules.tsv:267,n1_t4_composite_...",2,"p8347,p9737",[O;1>1;][.>=][C;3>3;]([.>-][O;1>1;])([C;3>3;](...
727,[C;D3:1]-[C;D2:2]-[N;D2:3]-[O;D1:4]>>[C;D3:1]-...,2,2,"156,7230",CC(C)(C)OC(=O)N[C@H](CNO)Cc1ccc(Oc2ccc(Cl)cc2)...,2,"2,4",[C;D3:1]-[C;D2:2]-[N;D2:3]-[O;D1:4]>>[C;D3:1]-...,"n1_t2_composite_rules.tsv:3892,n1_t4_composite...",2,"p5018,p9856",[O;1>1;][.>=][C;2>3;]([.>-][O;2>2;][C;1>1;])([...
765,[C;D3:1]-[C;D3:2]-1=[N;D2:3]-[O;D2:4]-[C;D4:5]...,2,2,"552,1510",CC1(C)OB(O)c2cc(F)c(C3=NOC(c4cc(Cl)cc(Cl)c4)(C...,1,4,[C;D3:1]-[C;D3:2]-1=[N;D2:3]-[O;D2:4]-[C;D4:5]...,n1_t4_composite_rules.tsv:1,2,"p9713,p9714",[C;3>3;][C;3>1;][->.]1[=>.][N;2>1;][O;2>1;][->...
1118,[C;D3:1]-[C;D2:2]-[N;D1:3]>>[C;D3:1]-[C;D3:2](...,2,2,"4,314",CCCCOC(=O)[C@@H]1CC[C@H](CN)CC1,1,4,[C;D2:1]-[N;D1:2]>>[C;D2:1]-[N;D2:2]=[N;D2+:4]...,n1_t4_composite_rules.tsv:0,1,p9711,[N;2>2;+](=[N;1>1;-])[.>=][N;1>1;0>-][->.][C;2...
1197,[C;D3:1]:1:[O:2]:[N;D2:3]:[C;D3:4]:2:[C;D3:5]:...,2,2,"4,314",Cc1onc2c1c(=O)n(C1CC(CN)CN(C(=O)OC(C)(C)C)C1)c...,1,4,[C;D2:1]-[N;D1:2]>>[C;D2:1]-[N;D2:2]=[N;D2+:4]...,n1_t4_composite_rules.tsv:0,1,p9712,[N;2>2;+](=[N;1>1;-])[.>=][N;1>1;0>-][->.][C;2...
...,...,...,...,...,...,...,...,...,...,...,...,...
8622,[O;D2:1]-[C;D2:2]-[N;D3:3](-[C;D3:4](=[O;D1:5]...,1,1,1837,CCOCN(C(=O)C(C)c1ccc2oc(-c3c(F)cccc3Cl)nc2c1)c...,1,4,[O;D2:1]-[C;D2:2]-[N;D3:3](-[C;D3:4](=[O:5])-[...,n1_t4_composite_rules.tsv:306,1,p9973,[Cl;1>1;][.>-][C;2>2;]([O;2>2;])[->.][N;3>1;](...
8626,[O;D2:1]-[C;D2:2]-[N;D3:3]:1:[C;D2:4]:[C:5]:[C...,1,1,1681,C[Si](C)(C)CCOCn1ccc2c(C(=NN)C3CCCCC3)ncnc21,1,4,[C:1]:[C;D3:3](:[N:2])-[C;D3:4](=[N;D2:5]-[N;D...,n1_t4_composite_rules.tsv:41,1,p9742,[O;1>1;][.>=][C;3>2;]([->.][C;3>3;]:1([.>-][I;...
8636,[O;D2:1]-[C;D2:2]-[O;D2:3]-[C;D2:4].[C;D2:5]-[...,1,1,2072,COCOCCCCCCCCCCCCCCCC=O,1,4,[C;D2:1]-[C;D2:2]=[O;D1:3]>>[C;D2:1]-[C;D2:2]-...,n1_t4_composite_rules.tsv:76,1,p9772,[O;1>1;][.>-][C;2>3;]([C;2>2;])=[O;1>1;].[Cl;1...
8708,[O;D2:1]-[N;D3:2](-[C;D2:3]-[C;D2:4])-[C;D3:5]...,1,1,2626,CON(CCCc1c(Cl)cc(Cl)cc1Cl)C(=O)c1cn(C)nc1C(F)F,1,4,[O;D2:1]-[N;D3:2](-[C;D2:3])-[C;D3:4](=[O;D1:5...,n1_t4_composite_rules.tsv:308,1,p9974,[O;1>1;][.>=][C;2>3;][->.]1([.>-][N;3>3;]([O;2...
8727,[S:1]:[C;D3:2](-[C;D3:3]-1=[N;D2:4]-[O;D2:5]-[...,1,1,960,COC(=O)c1sc(C2=NOC(c3cc(Cl)c(F)c(Cl)c3)(C(F)(F...,1,4,[C:1]:[C;D3:2](-[C;D3:3]-1=[N;D2:4]-[O;D2:5]-[...,n1_t4_composite_rules.tsv:37,1,p9738,[O;1>1;][.>=][C;4>3;][->.]1([->.][O;2>1;][N;2>...

In [28]:
y = 8252

In [29]:
alchemical_rule = smarts(df.iloc[y]['Alchemical_rule'])
alchemical_rule

In [30]:
route_id = int(df.iloc[y]['Reference'].split(',')[0])
route_id

307

In [31]:
svg = get_route_svg_from_json(routes_json, route_id, labeled=True)
display(SVG(svg))

In [ ]:
comp_rules = df.iloc[y]['Composite_rules'].split(' || ')
for comp_rule in comp_rules:
    rules = comp_rule.split('$')
    for rule in rules:
        display(smarts(rule))
    print(comp_rule)

In [34]:
df_sorted = df.sort_values(by="composite_rules_size", ascending=False)
df_sorted

,Alchemical_rule,popularity,route_ids_size,Reference,Target_molecules,composite_rules_size,Composite_rule_sizes,Composite_rules,Source_composite_rows,pseudo_reactions_size,Pseudo_reaction_ids,Alchemical_cgr
4,[C;D2:1]-[N;D3:2](-[C;D2:3])-[C;D2:5]-[C;D2:4]...,22,22,"89,178,473,991,1159,1380,1872,1911,2102,2182,2...",CC(=O)N[C@@H]1CC[C@@H](CCN2CCC(C(=O)c3ccc(F)s3...,9,2,[C;D2:1]-[C;D2:2]-[N;D3:3](-[C;D2:4])-[C;D2:5]...,"n1_t2_composite_rules.tsv:17,n1_t2_composite_r...",18,"p236,p237,p238,p239,p240,p241,p242,p597,p598,p...",[O;1>1;][.>-][C;2>2;]([->.][N;3>2;]([C;2>2;])[...
27,[C;D3:1]-[C;D2:2]-[N;D3:3](-[C;D2:4])-[C;D2:5]...,17,17,"57,325,418,1031,1309,1960,2165,3285,3389,3542,...",CC(C)(C)OC(=O)N1CC(CN2CCC3(CC2)CCN(Cc2ccc(Br)c...,8,2,[C;D2:1]-[N;D3:2](-[C;D2:3]-[C;D3:4])-[C;D2:5]...,"n1_t2_composite_rules.tsv:199,n1_t2_composite_...",14,"p522,p523,p524,p525,p526,p980,p981,p982,p983,p...",[O;1>1;][.>-][C;2>2;]([C;3>3;])[->.][N;3>2;]([...
2,[C;D3:1]-[C;D2:2]-[C;D2:3]#[N;D1:4]>>[C;D3:1]-...,23,23,"59,218,236,449,564,811,918,966,1059,1863,1894,...","C=COCC1CCC(CC#N)CC1,CC(C)(C)[Si](OCc1cccc(CC#N...",8,2,[C;D3:1]-[C;D2:2]-[C;D2:3]#[N;D1:4]>>[C;D3:1]-...,"n1_t2_composite_rules.tsv:30,n1_t2_composite_r...",19,"p335,p337,p339,p340,p341,p517,p519,p520,p521,p...",[O;1>1;][.>-][C;2>2;]([C;3>3;])[->.][C;2>1;]#[...
8,[C;D3:1]-[C;D2:2]-[C;D2:3]#[N;D1:4]>>[C;D3:1]-...,21,21,"50,59,209,218,274,307,449,863,966,1059,1418,20...","CC(C)(C)OC(=O)N[C@H]1CCCC[C@@H]1CC#N,CC(C)(C)O...",7,2,[C;D3:1]-[C;D2:2]-[C;D2:3]#[N;D1:4]>>[C;D3:1]-...,"n1_t2_composite_rules.tsv:231,n1_t2_composite_...",15,"p336,p338,p561,p562,p563,p564,p565,p1063,p1064...",[O;1>1;][.>-][C;2>2;]([->.][C;2>1;]#[N;1>1;])[...
126,[C;D2:1]-[N;D3:2](-[C;D2:3])-[C;D2:5]-[C;D2:4]...,7,7,"51,89,473,1380,2261,4912,6798",CC(=O)N[C@@H]1CC[C@@H](CCN2CCC(C(=O)c3ccc(F)s3...,6,"2,3",[C;D2:1]-[C;D2:2]-[N;D3:3](-[C;D2:4])-[C;D2:5]...,"n1_t2_composite_rules.tsv:2311,n1_t3_composite...",7,"p3491,p8114,p8115,p8541,p8558,p8728,p8740",[O;1>1;][.>=][C;2>3;]([.>-][O;2>2;][C;2>2;][C]...
...,...,...,...,...,...,...,...,...,...,...,...,...
3070,[C;D2:1]-[C;D2:2]-[Br;D1:3]>>[Br;D1:3]-[C;D4:4...,1,1,1903,CC(=O)OCCCCCCCCCCCCCCCCCBr,1,2,[C;D2:1]-[C;D2:2]-[Br;D1:3]>>[Br;D1:3]-[C;D4:5...,n1_t2_composite_rules.tsv:2216,1,p3397,[C]1[O][C;3>3;]([O;2>2;][.>-][C;2>2;]([C;2>2;]...
3069,[C;D2:1]-[C;D2:2]-[Br;D1:3]>>[Br;D1:3]-[C;D4:4...,1,1,119,BrCCCCCOCCCCBr,1,2,[Br;D1:1]-[C;D2:2]-[C;D2:3]>>[Br;D1:1]-[C;D4:5...,n1_t2_composite_rules.tsv:771,1,p2045,[C;4>4;]([Br;1>1;])([Br;1>1;])([Br;1>1;])[.>-]...
3068,[C;D2:1]-[C;D2:2]-[Br;D1:3]>>[Br;D1:3]-[C;D4:4...,1,1,7432,CC(C)(C)OC(=O)N1CC[C@H](NC(=O)COCCBr)C1,1,2,[C;D2:1]-[C;D2:2]-[Br;D1:3]>>[Br;D1:3]-[C;D4:5...,n1_t2_composite_rules.tsv:2215,1,p3396,[C]:1:[C]([C;2>2;][O;2>2;][.>-][C;2>2;]([C;2>2...
3067,[C;D2:1]-[C;D2:2]-[Br;D1:3]>>[Br;D0:3].[C;D2:1...,1,1,1297,O=S1(=O)CCC(CCBr)CC1,1,2,[C;D2:1]-[C;D2:2]-[Br;D1:3]>>[C;D2:1]-[C;D2:2]...,n1_t2_composite_rules.tsv:2224,1,p3405,[O;1>1;][.>-][C;2>2;]([->.][Br;1>0;])[C;2>2;]
8754,[S;D4:1]-[N;D3:2](-[C;D2:3]-[C;D3:4])-[C;D2:5]...,1,1,4582,O=S1(=O)N(Cc2ccc(Br)cc2F)CCCCN1c1ccccc1,1,2,[S;D4:1]-[N;D3:2](-[C;D2:3]-[C;D3:4])-[C;D2:5]...,n1_t2_composite_rules.tsv:7113,1,p8064,[Br;1>1;][.>-][C;2>2;]([->.][N;3>3;]([.>-][C;3...

In [38]:
z = 4
df.iloc[27]

Alchemical_rule          [C;D3:1]-[C;D2:2]-[N;D3:3](-[C;D2:4])-[C;D2:5]...
popularity                                                              17
route_ids_size                                                          17
Reference                57,325,418,1031,1309,1960,2165,3285,3389,3542,...
Target_molecules         CC(C)(C)OC(=O)N1CC(CN2CCC3(CC2)CCN(Cc2ccc(Br)c...
composite_rules_size                                                     8
Composite_rule_sizes                                                     2
Composite_rules          [C;D2:1]-[N;D3:2](-[C;D2:3]-[C;D3:4])-[C;D2:5]...
Source_composite_rows    n1_t2_composite_rules.tsv:199,n1_t2_composite_...
pseudo_reactions_size                                                   14
Pseudo_reaction_ids      p522,p523,p524,p525,p526,p980,p981,p982,p983,p...
Alchemical_cgr           [O;1>1;][.>-][C;2>2;]([C;3>3;])[->.][N;3>2;]([...
Name: 27, dtype: object

In [39]:
alchemical_rule_z = smarts(df.iloc[z]['Alchemical_rule'])
alchemical_rule_z

In [41]:
comp_rules = df.iloc[z]['Composite_rules'].split(' || ')
for comp_rule in comp_rules:
    rules = comp_rule.split('$')
    for rule in rules:
        display(smarts(rule))
    # print(comp_rule)

In [7]:
df_sorted_reactants = df.sort_values(by="output_reactants_num", ascending=False)
df_sorted_reactants

,Alchemical_rule,output_reactants_num,popularity,route_ids_size,Reference,Target_molecules,composite_rules_size,Composite_rule_sizes,Composite_rules,Source_composite_rows,pseudo_reactions_size,Pseudo_reaction_ids
3509,[C;D1:1]-[S;D4:2](=[O;D1:3])(=[O;D1:4])-[O;D2:...,6,1,1,97,CS(=O)(=O)OCC1Oc2c(Cl)cc(Br)cc2C1O,1,4,[C;D1:1]-[S;D4:2](=[O;D1:3])(=[O;D1:4])-[O;D2:...,n5_t4_composite_rules.tsv:214,1,p16350
2686,[C;D1:1]-[C;D2:2]-[O;D2:3]-[C;D3:4](:[C;D2:5])...,6,1,1,2157,CCOc1cc(Br)cc(F)c1OCC,1,3,[C;D1:1]-[C;D2:2]-[O;D2:3]-[C;D3:4]:[C;D3:5]-[...,n5_t3_composite_rules.tsv:715,1,p13795
9457,[O;D1:1]-[C;D3:2]:1:[C;D2:3]:[C;D3:4](-[C;D4:5...,5,1,1,1929,Oc1cc(C(F)(F)F)c2ccc3nc(-c4nnco4)cn3c2n1,1,4,[N:1]:[C;D3:2](-[C;D3:3]:1:[N;D2:4]:[N;D2:5]:[...,n5_t4_composite_rules.tsv:628,1,p16715
3475,[C;D1:1]-[S;D2:2]-[C;D3:3](-[S;D2:4]-[C;D1:5])...,5,1,1,3708,CSC(SC)=C(C#N)C(=O)c1ccc(Br)o1,1,2,[C;D1:1]-[S;D2:2]-[C;D3:3](-[S;D2:4]-[C;D1:5])...,n5_t2_composite_rules.tsv:3739,1,p6663
9845,[O;D1:1]=[N;D2:2]-[N;D3:3](-[C;D2:4])-[C;D3:5]...,5,1,1,3326,O=NN(CCCl)C(=O)N(CC1CC1)C1O[C@H](CO)[C@H](O)[C...,1,2,[O;D1:1]=[N;D2:2]-[N;D3:3](-[C;D2:4])-[C;D3:5]...,n5_t2_composite_rules.tsv:10047,1,p12732
...,...,...,...,...,...,...,...,...,...,...,...,...
4899,[C;D2:1]-[N;D3:2]:1:[C;D3:3](=[O;D1:4]):[N;D2:...,1,1,1,3988,Cc1ccc(Cn2c(=O)[nH]c3c(N)nc(OCC4CCOCC4)cc32)cn1,1,2,[C;D2:1]-[N;D3:2]:1:[C;D3:3](=[O;D1:4]):[N;D2:...,n5_t2_composite_rules.tsv:5095,1,p8001
6678,[C;D3:1]-[C;D3:2](=[C;D2:3]-[C;D2:4])-[C;D2:5]...,1,1,1,5635,COc1c(C)cc(C)cc1C(=O)C1=CCCCC1,1,2,[C:1]-[C;D3:2](=[O:3])-[C;D3:4](=[C;D2:5]-[C;D...,n5_t2_composite_rules.tsv:2232,1,p5263
355,[C;D2:1]-[C;D2:2]=[O;D1:3]>>[C;D2:1]-[C;D3:2](...,1,6,6,"389,2063,3020,3772,4429,8763","CC(C)(C)OC(=O)N[C@@H]1CC[C@@H](CC=O)OC1,CC(C)(...",3,"2,3",[C;D2:1]-[C;D2:2]=[O;D1:3]>>[C;D2:1]-[C;D2:2]-...,"n5_t2_composite_rules.tsv:436,n5_t2_composite_...",6,"p2177,p2178,p2179,p12371,p13159,p13160"
6682,[C;D3:1]-[C;D3:2](=[C;D2:3]-[C;D3:4])-[C;D2:5]...,1,1,1,595,COC(=O)C1=Cc2cccc(OCc3ccccc3)c2CC1,1,2,[O:1]-[C;D3:2](=[O:3])-[C;D3:4](=[C;D2:5]-[C;D...,n5_t2_composite_rules.tsv:9341,1,p12036
2707,[C;D1:1]-[C;D2:2]>>[C;D2:1](-[C;D2:2])-[O;D2:3...,1,1,1,8485,CC[C@H]1C(=O)OC[C@H](NC(=O)OC(C)(C)C)C(=O)O[C@...,1,2,[C;D1:1]-[C;D2:2]>>[C;D2:1](-[C;D2:2])-[I;D1:3...,n5_t2_composite_rules.tsv:3186,1,p6146

In [25]:
max_react_num = 3509
df.iloc[max_react_num]

Alchemical_rule          [C;D1:1]-[S;D4:2](=[O;D1:3])(=[O;D1:4])-[O;D2:...
output_reactants_num                                                     6
popularity                                                               1
route_ids_size                                                           1
Reference                                                               97
Target_molecules                        CS(=O)(=O)OCC1Oc2c(Cl)cc(Br)cc2C1O
composite_rules_size                                                     1
Composite_rule_sizes                                                     4
Composite_rules          [C;D1:1]-[S;D4:2](=[O;D1:3])(=[O;D1:4])-[O;D2:...
Source_composite_rows                        n5_t4_composite_rules.tsv:214
pseudo_reactions_size                                                    1
Pseudo_reaction_ids                                                 p16350
Name: 3509, dtype: object

In [26]:
smarts(df.iloc[max_react_num]['Alchemical_rule'])
# smiles(df.iloc[max_react_num]['Target_molecules'])

ValueError: min() arg is an empty sequence

In [27]:
tt_mol = smiles(df.iloc[max_react_num]['Target_molecules'])
tt_mol

In [ ]:


comp_rule = df.iloc[max_react_num]['Composite_rules']
split_composite_rule(comp_rule)

['[C;D1:1]-[S;D4:2](=[O;D1:3])(=[O;D1:4])-[O;D2:5]-[C;D2:6]>>[C;D1:1]-[S;D4:2](=[O;D1:3])(=[O;D1:4])-[Cl;D1:7].[O;D1:5]-[C;D2:6]',
 '[O;D1:1]-[C;D2:2]-[C;D3:3](-[O;D2:4]-[C;D3:5])-[C;D3:6]>>[O;D1:1]-[O;D2:9]-[C;D3:8](=[O:7])-[C:10]:1:[C:11]:[C:12]:[C:13]:[C:14](-[Cl:15]):[C:16]:1.[C;D1:2]=[C;D2:3]-[C;D3:6].[O;D1:4]-[C;D3:5]',
 '[C;D1:1]=[C;D2:2]-[C;D3:3](-[O;D1:4])-[C;D3:5]>>[C;D1:1]=[C;D2:2]-[Mg;D2:7]-[Br;D1:6].[C;D2:3](=[O;D1:4])-[C;D3:5]',
 '[O;D1:1]=[C;D2:2]-[C;D3:3](:[C;D3:4]):[C;D2:5]>>[C;D2:2]-1-[N;D3:9]-2-[C;D2:8]-[N:7]-3-[C:6]-[N:11](-[C;D2:10]-2)-[C;D2:12]-[N;D3:13]-1-[C;D2:14]-3.[O;D0:1].[C;D2:3](:[C;D3:4]):[C;D2:5]']

In [29]:
part_route = unwrap_composite_rule(str(tt_mol), comp_rule)
display(SVG(get_route_svg_from_json(part_route, 0)))

### Classification

In [4]:
from route_analysis.alchemical_rules.classify_alchemical import classify_alchemical_rules

In [5]:
from pathlib import Path

reference_one_step_rules_path = Path('../reference/pop_3_rules.tsv')
output = Path('../reference/')
summary_path = Path('../reference/')
summary = classify_alchemical_rules(alchemy_rules_path,
                                    reference_one_step_rules_path,
                                    output,
                                    summary_path)

In [6]:
summary

{'alchemical_rules_tsv': '../alchemical_out/n1_alchemical_rules.tsv',
 'default_rules_tsv': '../reference/pop_3_rules.tsv',
 'output': '../reference/n1_classified_alchemical_rules.tsv',
 'rows_seen': 8755,
 'positive': 8638,
 'negative': 117,
 'default_rules_parsed': 16436,
 'default_rule_parse_errors': 0,
 'alchemical_cgr_errors': 0,
 'summary_file': '../reference/n1_alchemical_rule_classification_summary.json'}

In [8]:
error_df = pd.read_csv('../resu_alchem/n5/n5_alchemical_rule_collection_errors.tsv', sep='\t')
error_df

,row_index,Target_smiles,Composite_rule,source_tsv,Composite_size,Route_ids
0,62,[cH:38]1[cH:39][c:40]([cH:42][cH:43][cH:37]1)[...,[O;D1:1]=[C;D3:2](-[N;D2:3]-[c;D3:4])-[c;D3:5]...,n5_t2,2,"648,1433,1867,3209,3810,4571,5827,6192,6435,86..."
1,62,[cH:14]1[cH:13][c:12]([cH:17][cH:16][cH:15]1)-...,[O;D1:1]=[C;D3:2](-[N;D2:3]-[c;D3:4])-[c;D3:5]...,n5_t2,2,"648,1433,1867,3209,3810,4571,5827,6192,6435,86..."
2,62,[CH2:14]1[CH2:15][N:16]([CH2:18][CH2:19][N:13]...,[O;D1:1]=[C;D3:2](-[N;D2:3]-[c;D3:4])-[c;D3:5]...,n5_t2,2,"648,1433,1867,3209,3810,4571,5827,6192,6435,86..."
3,81,[cH:12]1[cH:11][c:10]([cH:33][cH:32][c:13]1[CH...,[c;D3:1]-[C;D2:2]-[O;D2:3]-[c;D3:4]>>[O;D1:3]-...,n5_t2,2,"316,2717,3587,3623,4167,4786,5659,6055,7008,7969"
4,318,[F:9][C:8]([F:10])([F:11])[c:7]1[cH:6][cH:5][c...,[O;D1:1]=[C;D3:2](-[N;D2:3]-[c;D3:4](:[n:5]):[...,n5_t2,2,"1313,1473,1819,6696,7704"
...,...,...,...,...,...,...
154,50,[cH:4]1[cH:3][c:2]([cH:26][cH:25][c:5]1[CH:6](...,[C;D2:1]-[N;D2:2]-[C;D2:3]>>[C;D2:1]-[N;D3:2](...,n5_t5,5,3502
155,64,[CH2:2]([CH2:3][N:4]([CH2:5][CH2:6][CH3:7])[CH...,[C;D2:1]-[N;D3:2](-[C;D2:3])-[C;D2:4]-[C;D2:5]...,n5_t5,5,855
156,65,[O:3]([C:4](=[O:5])[CH2:6][CH2:7][CH2:8][N:9](...,[C;D2:1]-[N;D3:2](-[C;D2:3]-[C;D2:4])-[C;D2:5]...,n5_t5,5,1586
157,66,[CH2:15]1[CH2:16][N:17]([CH2:32][CH2:33][N:14]...,[C;D2:1]-[N;D3:2](-[C;D2:3]-[C;D3:4])-[C;D2:5]...,n5_t5,5,1805
158,84,[cH:29]1[cH:28][c:27]([cH:32][cH:31][cH:30]1)-...,[C;D3:1]-[N;D2:2]-[c;D3:3]:1:[c;D3:4]:[c:5]:[n...,n5_t5,5,2044

In [11]:
error_id = 0
er_mol = smiles(error_df.iloc[error_id]['Target_smiles'])
er_mol

In [19]:
# from unwrap_composite_rule
comp_rules = error_df.iloc[error_id]['Composite_rule']
comp_rule = '[C;D2:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[c;D3:5]>>[C;D2:1]-[N;D1:2].[C;D3:3](=[O;D1:4])(-[c;D3:5])-[O;D1:6]$[C;D3:1](=[O:2])(-[c:3])-[O;D1:4]>>[C;D3:1](=[O:2])(-[c:3])-[O;D2:4]-[C;D1:5]'
rules = split_composite_rule(comp_rules)
for rule in rules:
    print(rule)
    display(smarts(rule))
# unwrap_composite_rule(str(er_mol), comp_rules)

[O;D1:1]=[C;D3:2](-[N;D2:3]-[c;D3:4])-[c;D3:5](:[c:6]):[n:7]>>[N;D1:3]-[c;D3:4].[O;D1:1]=[C;D3:2](-[c;D3:5](:[c:6]):[n:7])-[O;D1:8]

[O:1]=[C;D3:2](-[c:3])-[O;D1:4]>>[O:1]=[C;D3:2](-[c:3])-[O;D2:4]-[C;D1:5]

In [16]:
smiles('Nc1cc(F)c(O)cc1F')

In [ ]:
rows_id = error_df.iloc[error_id]['row_index']
svg = get_route_svg_from_json(routes_json, rows_id, labeled=True)
display(SVG(svg))