In [ ]:
from chython import smarts, smiles
import pandas as pd

In [104]:
# df = pd.read_csv('../comp_output/n1/n1_t2_composite_rules.tsv', sep='\t')
df = pd.read_csv('../comp_output/n5/n5_t2_composite_rules.tsv', sep='\t')
# df = pd.read_csv('../comp_output/all/all_t2_composite_rules.tsv', sep='\t')
df

,Composite_rule,popularity,route_ids_size,Reference,Target_molecules
0,[C;D3:1]-[C;D2:2]=[O;D1:3]>>[C;D3:1]-[C;D2:2]-...,29,29,"48,178,395,402,475,583,1056,1105,1112,1419,148...","CCOC(=O)[C@@H]1CN(C(=O)OC(C)(C)C)C[C@H]1C=O,CO..."
1,[C;D3:1]-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D3:5]...,29,29,"180,213,440,537,785,833,1114,1461,1552,1589,17...",COc1cc2c(cc1F)n(C)c(=O)n2C[C@@H]1CC[C@@H](C(=O...
2,[C;D3:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[C;D3:5]...,28,28,"222,232,334,483,742,1025,1849,2196,2550,2847,3...",Cc1c(NC(=O)c2ccc(C(C)(C)C)cc2)cccc1B1OC(C)(C)C...
3,[C;D3:1]-[C;D2:2]=[O;D1:3]>>[C;D3:1]-[C;D2:2]-...,22,22,"372,386,738,896,961,1043,1287,1777,1815,2678,2...",Cc1nn(-c2c(F)cccc2C=O)cc1CN1CCC2(CC1)OCC(F)(F)...
4,[C;D3:1]-[N;D2:2]-[S;D4:3](=[O;D1:4])(=[O;D1:5...,22,22,"215,261,1195,1605,2978,3279,3497,3969,4047,479...",COc1cncnc1N1CCN(CCCc2c[nH]c3ccc(NS(=O)(=O)c4cc...
...,...,...,...,...,...
10260,[S;D4:1]-[N;D3:2](-[C;D2:3]-[O;D2:4])-[C;D3:5]...,1,1,532,CCc1cc(S(=O)(=O)N(COC)c2cc(Cl)cnc2Br)ccc1Cl
10261,[S;D4:1]-[N;D3:2]:1:[C;D3:3](-[C;D3:4]:2:[C:5]...,1,1,3712,CS(=O)(=O)n1c(-c2cnn(CC(F)(F)F)c2)cc2cnc(Br)cc21
10262,[S;D4:1]-[N;D3:2]:1:[C;D3:3](-[C;D3:4]:2:[C:5]...,1,1,3712,CS(=O)(=O)n1c(-c2cnn(CC(F)(F)F)c2)cc2cnc(Br)cc21
10263,[S;D4:1]-[N;D3:2]:1:[C;D3:3](:[C;D2:4]):[C;D3:...,1,1,344,CS(=O)(=O)n1c(C2CCCCC2)cc2cc([N+](=O)[O-])ccc21
10264,[S;D4:1]=[N;D2:2]-[C;D3:3](=[O;D1:4])-[C;D3:5]...,1,1,482,COC(=O)CCc1ccc(S(C)(=O)=NC(=O)c2cnc(N)c(C#Cc3c...

In [105]:
# x = 30
# x = 3802

x = 0
df.iloc[x]

Composite_rule      [C;D3:1]-[C;D2:2]=[O;D1:3]>>[C;D3:1]-[C;D2:2]-...
popularity                                                         29
route_ids_size                                                     29
Reference           48,178,395,402,475,583,1056,1105,1112,1419,148...
Target_molecules    CCOC(=O)[C@@H]1CN(C(=O)OC(C)(C)C)C[C@H]1C=O,CO...
Name: 0, dtype: object

In [106]:
mols = df.iloc[x]['Target_molecules'].split(',')
t_mol = mols[0]
display(smiles(t_mol))
t_mol

'CCOC(=O)[C@@H]1CN(C(=O)OC(C)(C)C)C[C@H]1C=O'

In [103]:
composite_rule = df.iloc[x]['Composite_rule']
rules = composite_rule.split('$')
for rule in rules:
    display(smarts(rule))
composite_rule

'[C;D3:1]-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D2:5]>>[C;D3:1]-[C;D3:2](=[O;D1:3])-[O;D1:6].[N;D1:4]-[C;D2:5]$[C:1]-[C;D3:2](=[O:3])-[O;D1:4]>>[C:1]-[C;D3:2](=[O:3])-[O;D2:4]-[C;D1:5]'

In [56]:
from synplan.utils.visualisation import get_route_svg_from_json
from route_analysis.composite_rules.unwrap import split_composite_rule, unwrap_composite_rule
from IPython.display import display, SVG

In [57]:
part_route = unwrap_composite_rule(t_mol, composite_rule)
part_route

{0: {'type': 'mol',
  'smiles': 'c1ccccc1NC(Nc2ccc3c(cn4c(=O)c(cnc4c3c2)C(=O)OCC)C)=O',
  'in_stock': False,
  'children': [{'type': 'reaction',
    'smiles': '[cH:18]1[cH:19][cH:20][cH:21][cH:22][c:17]1[NH:16][C:14]([NH:13][c:12]2[cH:23][cH:24][c:25]3[c:26]([cH:28][n:29]4[c:30](=[O:31])[c:6]([cH:7][n:8][c:9]4[c:10]3[cH:11]2)[C:4](=[O:5])[O:3][CH2:2][CH3:1])[CH3:27])=[O:15]>>[C:30]1([N:29]2[CH:28]=[C:26]([c:25]3[cH:24][cH:23][c:12]([N:13]=[C:14]=[O:15])[cH:11][c:10]3[C:9]2=[N:8][CH:7]=[C:6]1[C:4](=[O:5])[O:3][CH2:2][CH3:1])[CH3:27])=[O:31].[cH:19]1[cH:18][c:17]([cH:22][cH:21][cH:20]1)[NH2:16]',
    'rule_key': 'composite:1',
    'children': [{'type': 'mol',
      'smiles': 'C1(N2C=C(c3ccc(N=C=O)cc3C2=NC=C1C(=O)OCC)C)=O',
      'in_stock': True},
     {'type': 'mol',
      'smiles': 'c1cc(ccc1)N',
      'in_stock': False,
      'children': [{'type': 'reaction',
        'smiles': '[cH:19]1[cH:18][c:17]([cH:22][cH:21][cH:20]1)[NH2:16]>>[cH:18]1[cH:19][cH:20][cH:21][cH:22][c:17]1[N+:16]([O-:24])=[O:23]',
        'rule_key': 'composite:2',
        'children': [{'type': 'mol',
          'smiles': 'c1ccccc1[N+]([O-])=O',
          'in_stock': True}]}]}]}]}}

In [58]:
display(SVG(get_route_svg_from_json(part_route, 0)))

In [61]:
route_id = int(df.iloc[x]['Reference'].split(',')[0])
route_id

3983

In [13]:
import json
from IPython.display import SVG, display

from synplan.utils.visualisation import get_route_svg_from_json

routes_path = "../data/n1-routes.json"

with open(routes_path) as f:
    routes = json.load(f)

# PaRoutes file is a list, while get_route_svg_from_json expects route_id lookup.
routes_json = {i: route for i, route in enumerate(routes)}

In [63]:
svg = get_route_svg_from_json(routes_json, route_id, labeled=True)
display(SVG(svg))

In [15]:
svg = get_route_svg_from_json(routes_json, 3, labeled=True)
display(SVG(svg))

In [ ]:
### Convergent

In [4]:
x_svg = get_route_svg_from_json(routes_json, 17, labeled=True)
display(SVG(x_svg))

### Extract from route the composte rules

In [ ]:
import json
import pandas as pd
from argparse import Namespace
from pathlib import Path

from route_analysis.composite_rules.extract import (
    SynPlannerRuleExtractor,
    RouteProcessingStats,
    normalize_route_tree,
    extract_route_composites,
)

routes_path = Path("../data/n1-routes.json") # taken from PaRoutes
routes = json.load(routes_path.open())
routes_json = {i: route for i, route in enumerate(routes)}

route_id = 17
route = normalize_route_tree(routes_json[route_id])

args = Namespace(
    config=Path("../configs/rule_extraction_functional_groups.yaml"),
    environment_atom_count=1,
    include_rings=False,
    keep_leaving_groups=True,
    keep_incoming_groups=False,
    reactor_validation=False,
)

extractor = SynPlannerRuleExtractor.from_args(args)
stats = RouteProcessingStats()

comp_rule_res = extract_route_composites(
    route,
    extractor,
    min_length=2,
    max_length=5,
    stats=stats,
)

rows = []
for seq, target_molecules in sorted(
    comp_rule_res.items(),
    key=lambda item: (len(item[0]), "$".join(item[0])),
):
    rows.append({
        "size": len(seq),
        "Composite_rule": "$".join(seq),
        "Target_molecules": ",".join(sorted(target_molecules)),
        **{f"t{i+1}": rule for i, rule in enumerate(seq)},
    })

route_df = pd.DataFrame(rows)
display(route_df)
print(stats)

,size,Composite_rule,Target_molecules,t1,t2,t3,t4
0,2,[C;D3:1]-[C;D3:2]:1:[C;D3:3](-[O;D1:4]):[C;D3:...,Cc1cc(C)cc(-c2c(O)c3cc([N+](=O)[O-])c(Cl)cc3[n...,[C;D3:1]-[C;D3:2]:1:[C;D3:3](-[O;D1:4]):[C;D3:...,[C;D3:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[C;D2:5]...,NaN,NaN
1,2,[C;D3:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[C;D2:5]...,COC(=O)c1cc([N+](=O)[O-])c(Cl)cc1NC(=O)Cc1cc(C...,[C;D3:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[C;D2:5]...,[C;D3:1]-[N;D1:2]>>[C;D3:1]-[N;D2:2]-[C;D3:4](...,NaN,NaN
2,2,[C;D3:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[N;D2:5]...,Cc1cc(C)cc(-c2c(OCC[C@@H]3CCCCN3C(=O)OC(C)(C)C...,[C;D3:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[N;D2:5]...,[C;D3:1]-[N;D1:2]>>[C;D3:1]-[N;D3+:2](=[O;D1:3...,NaN,NaN
3,2,[C;D3:1]:1:[C;D3:2](-[O;D2:3]-[C;D2:4]):[C;D3:...,Cc1cc(C)cc(-c2c(OCC[C@@H]3CCCCN3C(=O)OC(C)(C)C...,[C;D3:1]:1:[C;D3:2](-[O;D2:3]-[C;D2:4]):[C;D3:...,[C;D3:1]-[C;D3:2]:1:[C;D3:3](-[O;D1:4]):[C;D3:...,NaN,NaN
4,3,[C;D3:1]-[C;D3:2]:1:[C;D3:3](-[O;D1:4]):[C;D3:...,Cc1cc(C)cc(-c2c(O)c3cc([N+](=O)[O-])c(Cl)cc3[n...,[C;D3:1]-[C;D3:2]:1:[C;D3:3](-[O;D1:4]):[C;D3:...,[C;D3:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[C;D2:5]...,[C;D3:1]-[N;D1:2]>>[C;D3:1]-[N;D2:2]-[C;D3:4](...,NaN
5,3,[C;D3:1]:1:[C;D3:2](-[O;D2:3]-[C;D2:4]):[C;D3:...,Cc1cc(C)cc(-c2c(OCC[C@@H]3CCCCN3C(=O)OC(C)(C)C...,[C;D3:1]:1:[C;D3:2](-[O;D2:3]-[C;D2:4]):[C;D3:...,[C;D3:1]-[C;D3:2]:1:[C;D3:3](-[O;D1:4]):[C;D3:...,[C;D3:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[C;D2:5]...,NaN
6,4,[C;D3:1]:1:[C;D3:2](-[O;D2:3]-[C;D2:4]):[C;D3:...,Cc1cc(C)cc(-c2c(OCC[C@@H]3CCCCN3C(=O)OC(C)(C)C...,[C;D3:1]:1:[C;D3:2](-[O;D2:3]-[C;D2:4]):[C;D3:...,[C;D3:1]-[C;D3:2]:1:[C;D3:3](-[O;D1:4]):[C;D3:...,[C;D3:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[C;D2:5]...,[C;D3:1]-[N;D1:2]>>[C;D3:1]-[N;D2:2]-[C;D3:4](...

RouteProcessingStats(routes_seen=0, routes_with_composites=0, reactions_seen=10, reaction_rule_cache_hits=0, reaction_rule_cache_misses=10, skipped_reactions=0, errors=0)

In [12]:
from chython import smarts

composite_rule = route_df.iloc[4]['Composite_rule']
rules = composite_rule.split('$')
for rule in rules:
    display(smarts(rule))

In [13]:
route

{'smiles': 'Cc1cc(C)cc(-c2c(OCC[C@@H]3CCCCN3)c3cc(NC(=O)NC4CC4)c(Cl)cc3[nH]c2=O)c1',
 'type': 'mol',
 'in_stock': False,
 'children': [{'type': 'reaction',
   'smiles': 'CC(C)(C)OC(=O)[N:18]1[C@H:13]([CH2:12][CH2:11][O:10][c:9]2[c:8](-[c:7]3[cH:6][c:4]([CH3:5])[cH:3][c:2]([CH3:1])[cH:36]3)[c:34](=[O:35])[nH:33][c:32]3[c:19]2[cH:20][c:21]([NH:22][C:23](=[O:24])[NH:25][CH:26]2[CH2:27][CH2:28]2)[c:29]([Cl:30])[cH:31]3)[CH2:14][CH2:15][CH2:16][CH2:17]1>>[CH3:1][c:2]1[cH:3][c:4]([CH3:5])[cH:6][c:7](-[c:8]2[c:9]([O:10][CH2:11][CH2:12][C@@H:13]3[CH2:14][CH2:15][CH2:16][CH2:17][NH:18]3)[c:19]3[cH:20][c:21]([NH:22][C:23](=[O:24])[NH:25][CH:26]4[CH2:27][CH2:28]4)[c:29]([Cl:30])[cH:31][c:32]3[nH:33][c:34]2=[O:35])[cH:36]1',
   'metadata': {'smiles': 'CC(C)(C)OC(=O)[N:18]1[C@H:13]([CH2:12][CH2:11][O:10][c:9]2[c:8](-[c:7]3[cH:6][c:4]([CH3:5])[cH:3][c:2]([CH3:1])[cH:36]3)[c:34](=[O:35])[nH:33][c:32]3[c:19]2[cH:20][c:21]([NH:22][C:23](=[O:24])[NH:25][CH:26]2[CH2:27][CH2:28]2)[c:29]([Cl:30])[cH:31]3)[CH2:14][CH2:15][CH2:16][CH2:17]1>>[CH3:1][c:2]1[cH:3][c:4]([CH3:5])[cH:6][c:7](-[c:8]2[c:9]([O:10][CH2:11][CH2:12][C@@H:13]3[CH2:14][CH2:15][CH2:16][CH2:17][NH:18]3)[c:19]3[cH:20][c:21]([NH:22][C:23](=[O:24])[NH:25][CH:26]4[CH2:27][CH2:28]4)[c:29]([Cl:30])[cH:31][c:32]3[nH:33][c:34]2=[O:35])[cH:36]1',
    'rsmi': 'CC(C)(C)OC(=O)[N:18]1[C@H:13]([CH2:12][CH2:11][O:10][c:9]2[c:8](-[c:7]3[cH:6][c:4]([CH3:5])[cH:3][c:2]([CH3:1])[cH:36]3)[c:34](=[O:35])[nH:33][c:32]3[c:19]2[cH:20][c:21]([NH:22][C:23](=[O:24])[NH:25][CH:26]2[CH2:27][CH2:28]2)[c:29]([Cl:30])[cH:31]3)[CH2:14][CH2:15][CH2:16][CH2:17]1>COc1ccccc1.O=C(O)C(F)(F)F>[CH3:1][c:2]1[cH:3][c:4]([CH3:5])[cH:6][c:7](-[c:8]2[c:9]([O:10][CH2:11][CH2:12][C@@H:13]3[CH2:14][CH2:15][CH2:16][CH2:17][NH:18]3)[c:19]3[cH:20][c:21]([NH:22][C:23](=[O:24])[NH:25][CH:26]4[CH2:27][CH2:28]4)[c:29]([Cl:30])[cH:31][c:32]3[nH:33][c:34]2=[O:35])[cH:36]1',
    'reaction_hash': 'JQDZGFWUEMWBRM-QHCPKHFHSA-N>>GTZRWABUMPGTQA-IBGZPJMESA-N',
    'ID': 'US06147088;;491564',
    'RingBreaker': False},
   'children': [{'smiles': 'Cc1cc(C)cc(-c2c(OCC[C@@H]3CCCCN3C(=O)OC(C)(C)C)c3cc(NC(=O)NC4CC4)c(Cl)cc3[nH]c2=O)c1',
     'type': 'mol',
     'in_stock': False,
     'children': [{'type': 'reaction',
       'smiles': 'ClC(Cl)(Cl)O[C:30](OC(Cl)(Cl)Cl)=[O:31].[CH3:1][c:2]1[cH:3][c:4]([CH3:5])[cH:6][c:7](-[c:8]2[c:9]([O:10][CH2:11][CH2:12][C@@H:13]3[CH2:14][CH2:15][CH2:16][CH2:17][N:18]3[C:19](=[O:20])[O:21][C:22]([CH3:23])([CH3:24])[CH3:25])[c:26]3[cH:27][c:28]([NH2:29])[c:36]([Cl:37])[cH:38][c:39]3[nH:40][c:41]2=[O:42])[cH:43]1.[NH2:32][CH:33]1[CH2:34][CH2:35]1>>[CH3:1][c:2]1[cH:3][c:4]([CH3:5])[cH:6][c:7](-[c:8]2[c:9]([O:10][CH2:11][CH2:12][C@@H:13]3[CH2:14][CH2:15][CH2:16][CH2:17][N:18]3[C:19](=[O:20])[O:21][C:22]([CH3:23])([CH3:24])[CH3:25])[c:26]3[cH:27][c:28]([NH:29][C:30](=[O:31])[NH:32][CH:33]4[CH2:34][CH2:35]4)[c:36]([Cl:37])[cH:38][c:39]3[nH:40][c:41]2=[O:42])[cH:43]1',
       'metadata': {'smiles': 'ClC(Cl)(Cl)O[C:30](OC(Cl)(Cl)Cl)=[O:31].[CH3:1][c:2]1[cH:3][c:4]([CH3:5])[cH:6][c:7](-[c:8]2[c:9]([O:10][CH2:11][CH2:12][C@@H:13]3[CH2:14][CH2:15][CH2:16][CH2:17][N:18]3[C:19](=[O:20])[O:21][C:22]([CH3:23])([CH3:24])[CH3:25])[c:26]3[cH:27][c:28]([NH2:29])[c:36]([Cl:37])[cH:38][c:39]3[nH:40][c:41]2=[O:42])[cH:43]1.[NH2:32][CH:33]1[CH2:34][CH2:35]1>>[CH3:1][c:2]1[cH:3][c:4]([CH3:5])[cH:6][c:7](-[c:8]2[c:9]([O:10][CH2:11][CH2:12][C@@H:13]3[CH2:14][CH2:15][CH2:16][CH2:17][N:18]3[C:19](=[O:20])[O:21][C:22]([CH3:23])([CH3:24])[CH3:25])[c:26]3[cH:27][c:28]([NH:29][C:30](=[O:31])[NH:32][CH:33]4[CH2:34][CH2:35]4)[c:36]([Cl:37])[cH:38][c:39]3[nH:40][c:41]2=[O:42])[cH:43]1',
        'rsmi': 'ClC(Cl)(Cl)O[C:30](OC(Cl)(Cl)Cl)=[O:31].[CH3:1][c:2]1[cH:3][c:4]([CH3:5])[cH:6][c:7](-[c:8]2[c:9]([O:10][CH2:11][CH2:12][C@@H:13]3[CH2:14][CH2:15][CH2:16][CH2:17][N:18]3[C:19](=[O:20])[O:21][C:22]([CH3:23])([CH3:24])[CH3:25])[c:26]3[cH:27][c:28]([NH2:29])[c:36]([Cl:37])[cH:38][c:39]3[nH:40][c:41]2=[O:42])[cH:43]1.[NH2:32][CH:33]1[CH2:34][CH2:35]1>CCOC(C)=O.c1ccncc1>[CH3:1][c:2]1[cH:3][c:4]([CH3:5])[cH:6][c:7](-[c:8]2[c:9]([O:10][CH2:11][CH2:12][C@@H:13]3[CH2:14][CH2:15][CH2:16][CH2:17][N:18]3[C:19](=[O:20])[O:21][C:22]([CH3:23])([CH3:24])[CH3:25])[c:26]3[cH:27][c:28]([NH:29][C:30](=[O:31])[NH:32][CH:33]4[CH2:34][CH2:35]4)[c:36]([Cl:37])[cH:38][c:39]3[nH:40][c:41]2=[O:42])[cH:43]1',
        'reaction_hash': 'HTJDQJBWANPRPF-UHFFFAOYSA-N.LBWXQYKOBUXKQI-FQEVSTJZSA-N.UCPYLLCMEDAXFR-UHFFFAOYSA-N>>JQDZGFWUEMWBRM-QHCPKHFHSA-N',
        'ID': 'US06147088;;491563',
        'RingBreaker': False},
       'children': [{'smiles': 'Cc1cc(C)cc(-c2c(OCC[C@@H]3CCCCN3C(=O)OC(C)(C)C)c3cc(N)c(Cl)cc3[nH]c2=O)c1',
         'type': 'mol',
         'in_stock': False,
         'children': [{'type': 'reaction',
           'smiles': 'O=[N+:29]([O-])[c:28]1[cH:27][c:26]2[c:9]([O:10][CH2:11][CH2:12][C@@H:13]3[CH2:14][CH2:15][CH2:16][CH2:17][N:18]3[C:19](=[O:20])[O:21][C:22]([CH3:23])([CH3:24])[CH3:25])[c:8](-[c:7]3[cH:6][c:4]([CH3:5])[cH:3][c:2]([CH3:1])[cH:37]3)[c:35](=[O:36])[nH:34][c:33]2[cH:32][c:30]1[Cl:31]>>[CH3:1][c:2]1[cH:3][c:4]([CH3:5])[cH:6][c:7](-[c:8]2[c:9]([O:10][CH2:11][CH2:12][C@@H:13]3[CH2:14][CH2:15][CH2:16][CH2:17][N:18]3[C:19](=[O:20])[O:21][C:22]([CH3:23])([CH3:24])[CH3:25])[c:26]3[cH:27][c:28]([NH2:29])[c:30]([Cl:31])[cH:32][c:33]3[nH:34][c:35]2=[O:36])[cH:37]1',
           'metadata': {'smiles': 'O=[N+:29]([O-])[c:28]1[cH:27][c:26]2[c:9]([O:10][CH2:11][CH2:12][C@@H:13]3[CH2:14][CH2:15][CH2:16][CH2:17][N:18]3[C:19](=[O:20])[O:21][C:22]([CH3:23])([CH3:24])[CH3:25])[c:8](-[c:7]3[cH:6][c:4]([CH3:5])[cH:3][c:2]([CH3:1])[cH:37]3)[c:35](=[O:36])[nH:34][c:33]2[cH:32][c:30]1[Cl:31]>>[CH3:1][c:2]1[cH:3][c:4]([CH3:5])[cH:6][c:7](-[c:8]2[c:9]([O:10][CH2:11][CH2:12][C@@H:13]3[CH2:14][CH2:15][CH2:16][CH2:17][N:18]3[C:19](=[O:20])[O:21][C:22]([CH3:23])([CH3:24])[CH3:25])[c:26]3[cH:27][c:28]([NH2:29])[c:30]([Cl:31])[cH:32][c:33]3[nH:34][c:35]2=[O:36])[cH:37]1',
            'rsmi': 'O=[N+:29]([O-])[c:28]1[cH:27][c:26]2[c:9]([O:10][CH2:11][CH2:12][C@@H:13]3[CH2:14][CH2:15][CH2:16][CH2:17][N:18]3[C:19](=[O:20])[O:21][C:22]([CH3:23])([CH3:24])[CH3:25])[c:8](-[c:7]3[cH:6][c:4]([CH3:5])[cH:3][c:2]([CH3:1])[cH:37]3)[c:35](=[O:36])[nH:34][c:33]2[cH:32][c:30]1[Cl:31]>Cl[Fe](Cl)Cl.NN.O.O.O.O.O.O>[CH3:1][c:2]1[cH:3][c:4]([CH3:5])[cH:6][c:7](-[c:8]2[c:9]([O:10][CH2:11][CH2:12][C@@H:13]3[CH2:14][CH2:15][CH2:16][CH2:17][N:18]3[C:19](=[O:20])[O:21][C:22]([CH3:23])([CH3:24])[CH3:25])[c:26]3[cH:27][c:28]([NH2:29])[c:30]([Cl:31])[cH:32][c:33]3[nH:34][c:35]2=[O:36])[cH:37]1',
            'reaction_hash': 'VIWLSTAPZWUKDK-FQEVSTJZSA-N>>LBWXQYKOBUXKQI-FQEVSTJZSA-N',
            'ID': 'US06147088;;491562',
            'RingBreaker': False},
           'children': [{'smiles': 'Cc1cc(C)cc(-c2c(OCC[C@@H]3CCCCN3C(=O)OC(C)(C)C)c3cc([N+](=O)[O-])c(Cl)cc3[nH]c2=O)c1',
             'type': 'mol',
             'in_stock': False,
             'children': [{'type': 'reaction',
               'smiles': 'O[c:9]1[c:8](-[c:7]2[cH:6][c:4]([CH3:5])[cH:3][c:2]([CH3:1])[cH:39]2)[c:37](=[O:38])[nH:36][c:35]2[c:26]1[cH:27][c:28]([N+:29](=[O:30])[O-:31])[c:32]([Cl:33])[cH:34]2.[OH:10][CH2:11][CH2:12][C@@H:13]1[CH2:14][CH2:15][CH2:16][CH2:17][N:18]1[C:19](=[O:20])[O:21][C:22]([CH3:23])([CH3:24])[CH3:25]>>[CH3:1][c:2]1[cH:3][c:4]([CH3:5])[cH:6][c:7](-[c:8]2[c:9]([O:10][CH2:11][CH2:12][C@@H:13]3[CH2:14][CH2:15][CH2:16][CH2:17][N:18]3[C:19](=[O:20])[O:21][C:22]([CH3:23])([CH3:24])[CH3:25])[c:26]3[cH:27][c:28]([N+:29](=[O:30])[O-:31])[c:32]([Cl:33])[cH:34][c:35]3[nH:36][c:37]2=[O:38])[cH:39]1',
               'metadata': {'smiles': 'O[c:9]1[c:8](-[c:7]2[cH:6][c:4]([CH3:5])[cH:3][c:2]([CH3:1])[cH:39]2)[c:37](=[O:38])[nH:36][c:35]2[c:26]1[cH:27][c:28]([N+:29](=[O:30])[O-:31])[c:32]([Cl:33])[cH:34]2.[OH:10][CH2:11][CH2:12][C@@H:13]1[CH2:14][CH2:15][CH2:16][CH2:17][N:18]1[C:19](=[O:20])[O:21][C:22]([CH3:23])([CH3:24])[CH3:25]>>[CH3:1][c:2]1[cH:3][c:4]([CH3:5])[cH:6][c:7](-[c:8]2[c:9]([O:10][CH2:11][CH2:12][C@@H:13]3[CH2:14][CH2:15][CH2:16][CH2:17][N:18]3[C:19](=[O:20])[O:21][C:22]([CH3:23])([CH3:24])[CH3:25])[c:26]3[cH:27][c:28]([N+:29](=[O:30])[O-:31])[c:32]([Cl:33])[cH:34][c:35]3[nH:36][c:37]2=[O:38])[cH:39]1',
                'rsmi': 'O[c:9]1[c:8](-[c:7]2[cH:6][c:4]([CH3:5])[cH:3][c:2]([CH3:1])[cH:39]2)[c:37](=[O:38])[nH:36][c:35]2[c:26]1[cH:27][c:28]([N+:29](=[O:30])[O-:31])[c:32]([Cl:33])[cH:34]2.[OH:10][CH2:11][CH2:12][C@@H:13]1[CH2:14][CH2:15][CH2:16][CH2:17][N:18]1[C:19](=[O:20])[O:21][C:22]([CH3:23])([CH3:24])[CH3:25]>CCOC(=O)N=NC(=O)OCC.c1ccc(P(c2ccccc2)c2ccccc2)cc1>[CH3:1][c:2]1[cH:3][c:4]([CH3:5])[cH:6][c:7](-[c:8]2[c:9]([O:10][CH2:11][CH2:12][C@@H:13]3[CH2:14][CH2:15][CH2:16][CH2:17][N:18]3[C:19](=[O:20])[O:21][C:22]([CH3:23])([CH3:24])[CH3:25])[c:26]3[cH:27][c:28]([N+:29](=[O:30])[O-:31])[c:32]([Cl:33])[cH:34][c:35]3[nH:36][c:37]2=[O:38])[cH:39]1',
                'reaction_hash': 'BHXCYYJAKSKFGK-UHFFFAOYSA-N.LTVQOFUGXMVESU-JTQLQIEISA-N>>VIWLSTAPZWUKDK-FQEVSTJZSA-N',
                'ID': 'US06147088;;491558',
                'RingBreaker': False},
               'children': [{'smiles': 'CC(C)(C)OC(=O)N1CCCC[C@H]1CCO',
                 'type': 'mol',
                 'in_stock': False,
                 'children': [{'type': 'reaction',
                   'smiles': 'C[O:16][C:15](=O)[CH2:14][C@H:13]1[N:8]([C:6]([O:5][C:2]([CH3:1])([CH3:3])[CH3:4])=[O:7])[CH2:9][CH2:10][CH2:11][CH2:12]1>>[CH3:1][C:2]([CH3:3])([CH3:4])[O:5][C:6](=[O:7])[N:8]1[CH2:9][CH2:10][CH2:11][CH2:12][C@H:13]1[CH2:14][CH2:15][OH:16]',
                   'metadata': {'smiles': 'C[O:16][C:15](=O)[CH2:14][C@H:13]1[N:8]([C:6]([O:5][C:2]([CH3:1])([CH3:3])[CH3:4])=[O:7])[CH2:9][CH2:10][CH2:11][CH2:12]1>>[CH3:1][C:2]([CH3:3])([CH3:4])[O:5][C:6](=[O:7])[N:8]1[CH2:9][CH2:10][CH2:11][CH2:12][C@H:13]1[CH2:14][CH2:15][OH:16]',
                    'rsmi': 'C[O:16][C:15](=O)[CH2:14][C@H:13]1[N:8]([C:6]([O:5][C:2]([CH3:1])([CH3:3])[CH3:4])=[O:7])[CH2:9][CH2:10][CH2:11][CH2:12]1>[Al+3].[HH].[HH].[HH].[HH].[Li+]>[CH3:1][C:2]([CH3:3])([CH3:4])[O:5][C:6](=[O:7])[N:8]1[CH2:9][CH2:10][CH2:11][CH2:12][C@H:13]1[CH2:14][CH2:15][OH:16]',
                    'reaction_hash': 'VJNWVGAZYYQKTF-JTQLQIEISA-N>>LTVQOFUGXMVESU-JTQLQIEISA-N',
                    'ID': 'US06147088;;491561',
                    'RingBreaker': False},
                   'children': [{'smiles': 'COC(=O)C[C@@H]1CCCCN1C(=O)OC(C)(C)C',
                     'type': 'mol',
                     'in_stock': True}]}]},
                {'smiles': 'Cc1cc(C)cc(-c2c(O)c3cc([N+](=O)[O-])c(Cl)cc3[nH]c2=O)c1',
                 'type': 'mol',
                 'in_stock': False,
                 'children': [{'type': 'reaction',
                   'smiles': 'CO[C:9](=[O:10])[c:11]1[cH:12][c:13]([N+:14](=[O:15])[O-:16])[c:17]([Cl:18])[cH:19][c:20]1[NH:21][C:22]([CH2:8][c:7]1[cH:6][c:4]([CH3:5])[cH:3][c:2]([CH3:1])[cH:24]1)=[O:23]>>[CH3:1][c:2]1[cH:3][c:4]([CH3:5])[cH:6][c:7](-[c:8]2[c:9]([OH:10])[c:11]3[cH:12][c:13]([N+:14](=[O:15])[O-:16])[c:17]([Cl:18])[cH:19][c:20]3[nH:21][c:22]2=[O:23])[cH:24]1',
                   'metadata': {'smiles': 'CO[C:9](=[O:10])[c:11]1[cH:12][c:13]([N+:14](=[O:15])[O-:16])[c:17]([Cl:18])[cH:19][c:20]1[NH:21][C:22]([CH2:8][c:7]1[cH:6][c:4]([CH3:5])[cH:3][c:2]([CH3:1])[cH:24]1)=[O:23]>>[CH3:1][c:2]1[cH:3][c:4]([CH3:5])[cH:6][c:7](-[c:8]2[c:9]([OH:10])[c:11]3[cH:12][c:13]([N+:14](=[O:15])[O-:16])[c:17]([Cl:18])[cH:19][c:20]3[nH:21][c:22]2=[O:23])[cH:24]1',
                    'rsmi': 'CO[C:9](=[O:10])[c:11]1[cH:12][c:13]([N+:14](=[O:15])[O-:16])[c:17]([Cl:18])[cH:19][c:20]1[NH:21][C:22]([CH2:8][c:7]1[cH:6][c:4]([CH3:5])[cH:3][c:2]([CH3:1])[cH:24]1)=[O:23]>C1CCOC1.C[Si](C)(C)N[Si](C)(C)C.[Na+]>[CH3:1][c:2]1[cH:3][c:4]([CH3:5])[cH:6][c:7](-[c:8]2[c:9]([OH:10])[c:11]3[cH:12][c:13]([N+:14](=[O:15])[O-:16])[c:17]([Cl:18])[cH:19][c:20]3[nH:21][c:22]2=[O:23])[cH:24]1',
                    'reaction_hash': 'SMMRLBSHMQQHFV-UHFFFAOYSA-N>>BHXCYYJAKSKFGK-UHFFFAOYSA-N',
                    'ID': 'US06147088;;491573',
                    'RingBreaker': True},
                   'children': [{'smiles': 'COC(=O)c1cc([N+](=O)[O-])c(Cl)cc1NC(=O)Cc1cc(C)cc(C)c1',
                     'type': 'mol',
                     'in_stock': False,
                     'children': [{'type': 'reaction',
                       'smiles': 'Cl[C:8](=[O:9])[CH2:10][c:11]1[cH:12][c:13]([CH3:14])[cH:15][c:16]([CH3:17])[cH:18]1.[CH3:1][O:2][C:3](=[O:4])[c:5]1[c:6]([NH2:7])[cH:19][c:20]([Cl:21])[c:22]([N+:23](=[O:24])[O-:25])[cH:26]1>>[CH3:1][O:2][C:3](=[O:4])[c:5]1[c:6]([NH:7][C:8](=[O:9])[CH2:10][c:11]2[cH:12][c:13]([CH3:14])[cH:15][c:16]([CH3:17])[cH:18]2)[cH:19][c:20]([Cl:21])[c:22]([N+:23](=[O:24])[O-:25])[cH:26]1',
                       'metadata': {'smiles': 'Cl[C:8](=[O:9])[CH2:10][c:11]1[cH:12][c:13]([CH3:14])[cH:15][c:16]([CH3:17])[cH:18]1.[CH3:1][O:2][C:3](=[O:4])[c:5]1[c:6]([NH2:7])[cH:19][c:20]([Cl:21])[c:22]([N+:23](=[O:24])[O-:25])[cH:26]1>>[CH3:1][O:2][C:3](=[O:4])[c:5]1[c:6]([NH:7][C:8](=[O:9])[CH2:10][c:11]2[cH:12][c:13]([CH3:14])[cH:15][c:16]([CH3:17])[cH:18]2)[cH:19][c:20]([Cl:21])[c:22]([N+:23](=[O:24])[O-:25])[cH:26]1',
                        'rsmi': 'Cl[C:8](=[O:9])[CH2:10][c:11]1[cH:12][c:13]([CH3:14])[cH:15][c:16]([CH3:17])[cH:18]1.[CH3:1][O:2][C:3](=[O:4])[c:5]1[c:6]([NH2:7])[cH:19][c:20]([Cl:21])[c:22]([N+:23](=[O:24])[O-:25])[cH:26]1>>[CH3:1][O:2][C:3](=[O:4])[c:5]1[c:6]([NH:7][C:8](=[O:9])[CH2:10][c:11]2[cH:12][c:13]([CH3:14])[cH:15][c:16]([CH3:17])[cH:18]2)[cH:19][c:20]([Cl:21])[c:22]([N+:23](=[O:24])[O-:25])[cH:26]1',
                        'reaction_hash': 'SVKISRAJLSOKLR-UHFFFAOYSA-N.TZKVHTHSNNHIGR-UHFFFAOYSA-N>>SMMRLBSHMQQHFV-UHFFFAOYSA-N',
                        'ID': 'US06147088;;491572',
                        'RingBreaker': False},
                       'children': [{'smiles': 'COC(=O)c1cc([N+](=O)[O-])c(Cl)cc1N',
                         'type': 'mol',
                         'in_stock': False,
                         'children': [{'type': 'reaction',
                           'smiles': 'CC(=O)[NH:7][c:6]1[c:5]([C:3]([O:2][CH3:1])=[O:4])[cH:15][c:11]([N+:12](=[O:13])[O-:14])[c:9]([Cl:10])[cH:8]1>>[CH3:1][O:2][C:3](=[O:4])[c:5]1[c:6]([NH2:7])[cH:8][c:9]([Cl:10])[c:11]([N+:12](=[O:13])[O-:14])[cH:15]1',
                           'metadata': {'smiles': 'CC(=O)[NH:7][c:6]1[c:5]([C:3]([O:2][CH3:1])=[O:4])[cH:15][c:11]([N+:12](=[O:13])[O-:14])[c:9]([Cl:10])[cH:8]1>>[CH3:1][O:2][C:3](=[O:4])[c:5]1[c:6]([NH2:7])[cH:8][c:9]([Cl:10])[c:11]([N+:12](=[O:13])[O-:14])[cH:15]1',
                            'rsmi': 'CC(=O)[NH:7][c:6]1[c:5]([C:3]([O:2][CH3:1])=[O:4])[cH:15][c:11]([N+:12](=[O:13])[O-:14])[c:9]([Cl:10])[cH:8]1>O=S(=O)(O)O>[CH3:1][O:2][C:3](=[O:4])[c:5]1[c:6]([NH2:7])[cH:8][c:9]([Cl:10])[c:11]([N+:12](=[O:13])[O-:14])[cH:15]1',
                            'reaction_hash': 'XIMSLPBLUXHJIS-UHFFFAOYSA-N>>SVKISRAJLSOKLR-UHFFFAOYSA-N',
                            'ID': 'US06147088;;491576',
                            'RingBreaker': False},
                           'children': [{'smiles': 'COC(=O)c1cc([N+](=O)[O-])c(Cl)cc1NC(C)=O',
                             'type': 'mol',
                             'in_stock': False,
                             'children': [{'type': 'reaction',
                               'smiles': 'O[N+:15](=[O:16])[O-:17].[CH3:1][O:2][C:3](=[O:4])[c:5]1[c:6]([NH:7][C:8]([CH3:9])=[O:10])[cH:11][c:12]([Cl:13])[cH:14][cH:18]1>>[CH3:1][O:2][C:3](=[O:4])[c:5]1[c:6]([NH:7][C:8]([CH3:9])=[O:10])[cH:11][c:12]([Cl:13])[c:14]([N+:15](=[O:16])[O-:17])[cH:18]1',
                               'metadata': {'smiles': 'O[N+:15](=[O:16])[O-:17].[CH3:1][O:2][C:3](=[O:4])[c:5]1[c:6]([NH:7][C:8]([CH3:9])=[O:10])[cH:11][c:12]([Cl:13])[cH:14][cH:18]1>>[CH3:1][O:2][C:3](=[O:4])[c:5]1[c:6]([NH:7][C:8]([CH3:9])=[O:10])[cH:11][c:12]([Cl:13])[c:14]([N+:15](=[O:16])[O-:17])[cH:18]1',
                                'rsmi': 'O[N+:15](=[O:16])[O-:17].[CH3:1][O:2][C:3](=[O:4])[c:5]1[c:6]([NH:7][C:8]([CH3:9])=[O:10])[cH:11][c:12]([Cl:13])[cH:14][cH:18]1>O=S(=O)(O)O>[CH3:1][O:2][C:3](=[O:4])[c:5]1[c:6]([NH:7][C:8]([CH3:9])=[O:10])[cH:11][c:12]([Cl:13])[c:14]([N+:15](=[O:16])[O-:17])[cH:18]1',
                                'reaction_hash': 'DKFAYQCXBCDRFR-UHFFFAOYSA-N.GRYLNZFGIOXLOG-UHFFFAOYSA-N>>XIMSLPBLUXHJIS-UHFFFAOYSA-N',
                                'ID': 'US06147088;;491575',
                                'RingBreaker': False},
                               'children': [{'smiles': 'COC(=O)c1ccc(Cl)cc1NC(C)=O',
                                 'type': 'mol',
                                 'in_stock': True},
                                {'smiles': 'O=[N+]([O-])O',
                                 'type': 'mol',
                                 'in_stock': True}]}]}]}]},
                        {'smiles': 'Cc1cc(C)cc(CC(=O)Cl)c1',
                         'type': 'mol',
                         'in_stock': False,
                         'children': [{'type': 'reaction',
                           'smiles': 'O=C(Cl)C(=O)[Cl:11].O[C:9]([CH2:8][c:7]1[cH:6][c:4]([CH3:5])[cH:3][c:2]([CH3:1])[cH:12]1)=[O:10]>>[CH3:1][c:2]1[cH:3][c:4]([CH3:5])[cH:6][c:7]([CH2:8][C:9](=[O:10])[Cl:11])[cH:12]1',
                           'metadata': {'smiles': 'O=C(Cl)C(=O)[Cl:11].O[C:9]([CH2:8][c:7]1[cH:6][c:4]([CH3:5])[cH:3][c:2]([CH3:1])[cH:12]1)=[O:10]>>[CH3:1][c:2]1[cH:3][c:4]([CH3:5])[cH:6][c:7]([CH2:8][C:9](=[O:10])[Cl:11])[cH:12]1',
                            'rsmi': 'O=C(Cl)C(=O)[Cl:11].O[C:9]([CH2:8][c:7]1[cH:6][c:4]([CH3:5])[cH:3][c:2]([CH3:1])[cH:12]1)=[O:10]>CN(C)C=O>[CH3:1][c:2]1[cH:3][c:4]([CH3:5])[cH:6][c:7]([CH2:8][C:9](=[O:10])[Cl:11])[cH:12]1',
                            'reaction_hash': 'CTSLXHKWHWQRSH-UHFFFAOYSA-N.HDNBKTWQBJJYPD-UHFFFAOYSA-N>>TZKVHTHSNNHIGR-UHFFFAOYSA-N',
                            'ID': 'US06147088;;491577',
                            'RingBreaker': False},
                           'children': [{'smiles': 'Cc1cc(C)cc(CC(=O)O)c1',
                             'type': 'mol',
                             'in_stock': True},
                            {'smiles': 'O=C(Cl)C(=O)Cl',
                             'type': 'mol',
                             'in_stock': True}]}]}]}]}]}]}]}]}]}]},
        {'smiles': 'NC1CC1', 'type': 'mol', 'in_stock': True},
        {'smiles': 'O=C(OC(Cl)(Cl)Cl)OC(Cl)(Cl)Cl',
         'type': 'mol',
         'in_stock': True}]}]}]}]}

In [42]:
from route_analysis.utils.cgr_process import extract_one_route_cgr
from chython import depict_settings

depict_settings(aam=False, monochrome=False)

route_cgr = extract_one_route_cgr(
               route,
               check_trans_error=True,
               use_mapped_reaction_smiles=True,
           )


route_cgr