In [1]:
from chython import smarts, smiles
import pandas as pd

In [2]:
alchemy_rules_path = '../alchemical_out/n1_alchemical_rules.tsv'
# alchemy_rules_path = '../alchemical_out/n5_alchemical_rules.tsv'
df = pd.read_csv(alchemy_rules_path, sep='\t')
df

,Alchemical_rule,popularity,route_ids_size,Reference,Target_molecules,composite_rules_size,Composite_rule_sizes,Composite_rules,Source_composite_rows,pseudo_reactions_size,Pseudo_reaction_ids,Alchemical_cgr
0,[C;D3:1]-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D2:5]...,26,26,"6,1168,1257,1558,1571,1587,1706,1861,2142,2398...",C=CCC(CC=C)(COc1cc(C)c(-c2ccc(C(F)(F)F)cc2)c(C...,2,2,[C;D3:1]-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D2:5]...,"n1_t2_composite_rules.tsv:0,n1_t2_composite_ru...",6,"p2,p5,p826,p827,p828,p829",[O;2>2;]([C;1>1;])[.>-][C;3>3;](=[O;1>1;])([->...
1,[C;D3:1]-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D3:5]...,24,24,"37,376,494,666,707,873,1053,1127,1200,1386,174...",CC(=O)NCC(C(=O)Nc1ccccc1)c1ccc(C(=O)OC(C)(C)C)...,4,"2,3",[C;D3:1]-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D3:5]...,"n1_t2_composite_rules.tsv:1,n1_t3_composite_ru...",21,"p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p33,p3...",[O;2>2;]([C;1>1;])[.>-][C;3>3;]([C;3>3;])(=[O;...
2,[C;D3:1]-[C;D2:2]-[C;D2:3]#[N;D1:4]>>[C;D3:1]-...,23,23,"59,218,236,449,564,811,918,966,1059,1863,1894,...","C=COCC1CCC(CC#N)CC1,CC(C)(C)[Si](OCc1cccc(CC#N...",8,2,[C;D3:1]-[C;D2:2]-[C;D2:3]#[N;D1:4]>>[C;D3:1]-...,"n1_t2_composite_rules.tsv:30,n1_t2_composite_r...",19,"p335,p337,p339,p340,p341,p517,p519,p520,p521,p...",[O;1>1;][.>-][C;2>2;]([C;3>3;])[->.][C;2>1;]#[...
3,[C;D3:1]-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D2:5]...,23,23,"6,543,1168,1257,1571,1706,2142,2398,2839,3268,...",C=CCc1c(C(=O)NCc2c(C(C)CC=C)cc(C)nc2OC)cccc1N(...,2,"2,3",[C;D3:1]-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D2:5]...,"n1_t2_composite_rules.tsv:0,n1_t3_composite_ru...",18,"p0,p1,p6,p7,p8,p9,p10,p11,p12,p13,p14,p16,p17,...",[O;2>2;]([C;1>1;])[.>-][C;3>3;]([C;3>3;])(=[O;...
4,[C;D2:1]-[N;D3:2](-[C;D2:3])-[C;D2:5]-[C;D2:4]...,22,22,"89,178,473,991,1159,1380,1872,1911,2102,2182,2...",CC(=O)N[C@@H]1CC[C@@H](CCN2CCC(C(=O)c3ccc(F)s3...,9,2,[C;D2:1]-[C;D2:2]-[N;D3:3](-[C;D2:4])-[C;D2:5]...,"n1_t2_composite_rules.tsv:17,n1_t2_composite_r...",18,"p236,p237,p238,p239,p240,p241,p242,p597,p598,p...",[O;1>1;][.>-][C;2>2;]([->.][N;3>2;]([C;2>2;])[...
...,...,...,...,...,...,...,...,...,...,...,...,...
8750,[S;D4:1]-[C;D3:2]:1:[N;D2:3]:[N;D2:4]:[C;D3:5]...,1,1,1190,O=S(=O)(c1ccccc1)c1n[nH]c2ccc(OCCNC3CC3)cc12,1,3,[C;D2:1]-[C;D2:2]-[N;D2:3]-[C;D3:4]>>[C;D2:1]-...,n1_t3_composite_rules.tsv:462,1,p8529,[O;2>2;]([S;4>4;]([C]:1:[C]:[C]:[C]([C]):[C]:[...
8751,[S;D4:1]-[C;D3:2]:1:[N;D2:3]:[N;D2:4]:[C;D3:5]...,1,1,2210,O=S(=O)(c1cccc2ccccc12)c1n[nH]c2c(OC(CCl)CCl)c...,1,2,[S;D4:1]-[C;D3:2]:1:[N;D2:3]:[N;D2:4]:[C;D3:5]...,n1_t2_composite_rules.tsv:7103,1,p8054,[O;1>1;][.>-][N;2>2;][:>.]1([.>=][O;1>1;])[:>....
8752,[S;D4:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[N;D2:5]...,1,1,1013,COCCc1sc(S(=O)(=O)NC(=O)Nc2cc(SC)cc(NCCF)n2)cc1C,1,2,[S;D4:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[N;D2:5]...,n1_t2_composite_rules.tsv:7104,1,p8055,[Cl;1>1;][.>-][C;3>3;]([.>-][O;2>2;][C;3>3;]:1...
8753,[S;D4:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[N;D2:5]...,1,1,4006,C[Se]c1ccccc1S(=O)(=O)NC(=O)Nc1nc(C)cc(C)n1,1,2,[S;D4:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[N;D2:5]...,n1_t2_composite_rules.tsv:7105,1,p8056,[C;2>2;][.>-]1[.>-][C;3>2;][:>.]2([N;2>2;][->=...
8754,[S;D4:1]-[N;D3:2](-[C;D2:3]-[C;D3:4])-[C;D2:5]...,1,1,4582,O=S1(=O)N(Cc2ccc(Br)cc2F)CCCCN1c1ccccc1,1,2,[S;D4:1]-[N;D3:2](-[C;D2:3]-[C;D3:4])-[C;D2:5]...,n1_t2_composite_rules.tsv:7113,1,p8064,[Br;1>1;][.>-][C;2>2;]([->.][N;3>3;]([.>-][C;3...

In [14]:
x = 2
df.iloc[x]

Alchemical_rule          [C;D3:1]-[C;D2:2]-[C;D2:3]#[N;D1:4]>>[C;D3:1]-...
popularity                                                              23
route_ids_size                                                          23
Reference                59,218,236,449,564,811,918,966,1059,1863,1894,...
Target_molecules         C=COCC1CCC(CC#N)CC1,CC(C)(C)[Si](OCc1cccc(CC#N...
composite_rules_size                                                     8
Composite_rule_sizes                                                     2
Composite_rules          [C;D3:1]-[C;D2:2]-[C;D2:3]#[N;D1:4]>>[C;D3:1]-...
Source_composite_rows    n1_t2_composite_rules.tsv:30,n1_t2_composite_r...
pseudo_reactions_size                                                   19
Pseudo_reaction_ids      p335,p337,p339,p340,p341,p517,p519,p520,p521,p...
Alchemical_cgr           [O;1>1;][.>-][C;2>2;]([C;3>3;])[->.][C;2>1;]#[...
Name: 2, dtype: object

In [15]:
alchemical_rule = smarts(df.iloc[x]['Alchemical_rule'])
alchemical_rule

In [16]:
comp_rules = df.iloc[x]['Composite_rules'].split(' || ')
for comp_rule in comp_rules:
    rules = comp_rule.split('$')
    for rule in rules:
        display(smarts(rule))
    print(comp_rule)

[C;D3:1]-[C;D2:2]-[C;D2:3]#[N;D1:4]>>[C;D3:1]-[C;D2:2]-[Br;D1:5].[C;D1:3]#[N;D1:4]$[C;D3:1]-[C;D2:2]-[Br;D1:3]>>[Br;D1:3]-[C;D4:5](-[Br;D1:4])(-[Br;D1:6])-[Br;D1:7].[C;D3:1]-[C;D2:2]-[O;D1:8]

[C;D3:1]-[C;D2:2]-[C;D2:3]#[N;D1:4]>>[C;D3:1]-[C;D2:2]-[Br;D1:5].[C;D1:3]#[N;D1:4]$[C;D3:1]-[C;D2:2]-[Br;D1:3]>>[Br;D1:3]-[P;D3:5](-[Br;D1:4])-[Br;D1:6].[C;D3:1]-[C;D2:2]-[O;D1:7]

[C;D3:1]-[C;D2:2]-[C;D2:3]#[N;D1:4]>>[C;D3:1]-[C;D2:2]-[Br;D1:5].[C;D1:3]#[N;D1:4]$[C;D3:1]-[C;D2:2]-[Br;D1:3]>>[Br;D1:3]-[P;D5:5](-[Br;D1:4])(-[C;D3:6]:1:[C:7]:[C:8]:[C:9]:[C:10]:[C:11]:1)(-[C;D3:12]:2:[C:13]:[C:14]:[C:15]:[C:16]:[C:17]:2)-[C;D3:18]:3:[C:19]:[C:20]:[C:21]:[C:22]:[C:23]:3.[C;D3:1]-[C;D2:2]-[O;D1:24]

[C;D3:1]-[C;D2:2]-[C;D2:3]#[N;D1:4]>>[C;D3:1]-[C;D2:2]-[Cl;D1:5].[C;D1:3]#[N;D1:4]$[C;D3:1]-[C;D2:2]-[Cl;D1:3]>>[Cl;D1:3]-[C;D2:5]-[Cl;D1:4].[C;D3:1]-[C;D2:2]-[O;D1:6]

[C;D3:1]-[C;D2:2]-[C;D2:3]#[N;D1:4]>>[C;D3:1]-[C;D2:2]-[Cl;D1:5].[C;D1:3]#[N;D1:4]$[C;D3:1]-[C;D2:2]-[Cl;D1:3]>>[Cl;D1:3]-[S;D3:5](=[O;D1:4])-[Cl;D1:6].[C;D3:1]-[C;D2:2]-[O;D1:7]

[C;D3:1]-[C;D2:2]-[C;D2:3]#[N;D1:4]>>[C;D3:1]-[C;D2:2]-[Cl;D1:5].[C;D1:3]#[N;D1:4]$[C;D3:1]-[C;D2:2]-[Cl;D1:3]>>[Cl;D1:3]-[S;D4:5](-[C;D1:4])(=[O;D1:6])=[O;D1:7].[C;D3:1]-[C;D2:2]-[O;D1:8]

[C;D3:1]-[C;D2:2]-[C;D2:3]#[N;D1:4]>>[C;D3:1]-[C;D2:2]-[O;D2:13]-[S;D4:10](-[C:9]:1:[C:8]:[C:7]:[C:6](-[C:5]):[C:15]:[C:14]:1)(=[O:11])=[O:12].[C;D1:3]#[N;D1:4]$[C:1]-[C:2]:1:[C:3]:[C:4]:[C;D3:5](-[S;D4:6](=[O;D1:7])(=[O;D1:8])-[O;D2:9]-[C;D2:10]):[C:11]:[C:12]:1>>[C:1]-[C:2]:1:[C:3]:[C:4]:[C;D3:5](-[S;D4:6](=[O;D1:7])(=[O;D1:8])-[Cl;D1:13]):[C:11]:[C:12]:1.[O;D1:9]-[C;D2:10]

[C;D3:1]-[C;D2:2]-[C;D2:3]#[N;D1:4]>>[C;D3:1]-[C;D2:2]-[O;D2:9]-[S;D4:6](-[C:5])(=[O:7])=[O:8].[C;D1:3]#[N;D1:4]$[C;D2:1]-[O;D2:2]-[S;D4:3](-[C;D1:4])(=[O;D1:5])=[O;D1:6]>>[S;D4:3](-[C;D1:4])(=[O;D1:5])(=[O;D1:6])-[Cl;D1:7].[C;D2:1]-[O;D1:2]

In [17]:
mols = df.iloc[x]['Target_molecules'].split(',')

In [18]:
t_mol = mols[1]
display(smiles(t_mol))
t_mol

'CC(C)(C)[Si](OCc1cccc(CC#N)c1)(c1ccccc1)c1ccccc1'

In [ ]:
from synplan.utils.visualisation import get_route_svg_from_json
from alchems.alchemical_rules.unwrap_alchemical import unwrap_alchemical_rule
from IPython.display import display, SVG

In [22]:
str(alchemical_rule)

'[C;D3:1]-[C;D2:2]-[C;D2:3]#[N;D1:4]>>[C;D1:3]#[N;D1:4].[C;D3:1]-[C;D2:2]-[O;D1:5]'

In [23]:
part_route = unwrap_alchemical_rule(t_mol, str(alchemical_rule))
part_route

{0: {'type': 'mol',
  'smiles': 'c1ccccc1[Si](c2ccccc2)(C(C)(C)C)OCc3cc(CC#N)ccc3',
  'in_stock': False,
  'children': [{'type': 'reaction',
    'smiles': '[cH:18]1[cH:19][cH:20][cH:21][cH:22][c:17]1[Si:5]([c:23]2[cH:24][cH:25][cH:26][cH:27][cH:28]2)([C:2]([CH3:1])([CH3:3])[CH3:4])[O:6][CH2:7][c:8]3[cH:16][c:12]([CH2:13][C:14]#[N:15])[cH:11][cH:10][cH:9]3>>[N:15]#[CH:14].[cH:18]1[cH:19][cH:20][cH:21][cH:22][c:17]1[Si:5]([c:23]2[cH:24][cH:25][cH:26][cH:27][cH:28]2)([C:2]([CH3:1])([CH3:3])[CH3:4])[O:6][CH2:7][c:8]3[cH:9][cH:10][cH:11][c:12]([CH2:13][OH:29])[cH:16]3',
    'rule_key': 'alchemical:1',
    'children': [{'type': 'mol',
      'smiles': 'c1ccccc1[Si](c2ccccc2)(C(C)(C)C)OCc3cccc(CO)c3',
      'in_stock': True},
     {'type': 'mol', 'smiles': 'N#C', 'in_stock': True}]}]}}

In [24]:
display(SVG(get_route_svg_from_json(part_route, 0)))

In [19]:
route_id = int(df.iloc[x]['Reference'].split(',')[0])
route_id

264

In [26]:
import json
import sys
import os
from IPython.display import SVG, display

os.environ.setdefault("MPLCONFIGDIR", "/private/tmp/matplotlib-codex")
os.environ.setdefault("XDG_CACHE_HOME", "/private/tmp/codex-cache")

sys.path.insert(0, "/Users/almazgil/Desktop/projects/Retro-BLEU/composite_rules")

from synplan.utils.visualisation import get_route_svg_from_json

routes_path = "/Users/almazgil/Desktop/projects/Retro-BLEU/PaRoutes/data/n1-routes.json"

with open(routes_path) as f:
    routes = json.load(f)

# PaRoutes file is a list, while get_route_svg_from_json expects route_id lookup.
routes_json = {i: route for i, route in enumerate(routes)}

In [18]:
svg = get_route_svg_from_json(routes_json, route_id, labeled=True)
display(SVG(svg))

In [ ]:
new_df = df[df["Composite_rule_sizes"].astype(str).str.contains(",", na=False)]
new_df.shape

In [16]:
s = df["Composite_rule_sizes"].astype(str).str.strip()

# rows with multiple values, e.g. "2,3"
is_mixed = s.str.contains(",", na=False)

# counts for single values only
single_counts = s[~is_mixed].value_counts().sort_index()

# add mixed count
stats = pd.concat([
    single_counts,
    pd.Series({"mixed": is_mixed.sum()})
])

stats

2        6882
3        1538
4         261
5          35
mixed      39
dtype: int64

In [17]:
combo_stats = s.value_counts().sort_index().reset_index()
combo_stats.columns = ["Composite_rule_sizes", "count"]
combo_stats

  Composite_rule_sizes  count
0                    2   6882
1                  2,3     37
2                  2,4      1
3                    3   1538
4                  3,4      1
5                    4    261
6                    5     35

In [25]:
val = "4"

rows_with_val = df[
    df["Composite_rule_sizes"]
    .astype(str)
    .str.split(",")
    .apply(lambda xs: val in [x.strip() for x in xs])
]
rows_with_val

,Alchemical_rule,popularity,route_ids_size,Reference,Target_molecules,composite_rules_size,Composite_rule_sizes,Composite_rules,Source_composite_rows,pseudo_reactions_size,Pseudo_reaction_ids,Alchemical_cgr
589,[C:1]:[C;D3:2](-[C;D3:3](=[N;D1:4])-[N;D2:5]-[...,2,2,"1621,2578","Cc1cc(C(=N)NO)nc(Cl)n1,Cc1cc(C(=N)NO)nc(NC(C)C)n1",2,"3,4",[C:1]:[C;D3:2](-[C;D3:3](=[N;D1:4])-[N;D2:5]-[...,"n1_t3_composite_rules.tsv:267,n1_t4_composite_...",2,"p8347,p9737",[O;1>1;][.>=][C;3>3;]([.>-][O;1>1;])([C;3>3;](...
727,[C;D3:1]-[C;D2:2]-[N;D2:3]-[O;D1:4]>>[C;D3:1]-...,2,2,"156,7230",CC(C)(C)OC(=O)N[C@H](CNO)Cc1ccc(Oc2ccc(Cl)cc2)...,2,"2,4",[C;D3:1]-[C;D2:2]-[N;D2:3]-[O;D1:4]>>[C;D3:1]-...,"n1_t2_composite_rules.tsv:3892,n1_t4_composite...",2,"p5018,p9856",[O;1>1;][.>=][C;2>3;]([.>-][O;2>2;][C;1>1;])([...
765,[C;D3:1]-[C;D3:2]-1=[N;D2:3]-[O;D2:4]-[C;D4:5]...,2,2,"552,1510",CC1(C)OB(O)c2cc(F)c(C3=NOC(c4cc(Cl)cc(Cl)c4)(C...,1,4,[C;D3:1]-[C;D3:2]-1=[N;D2:3]-[O;D2:4]-[C;D4:5]...,n1_t4_composite_rules.tsv:1,2,"p9713,p9714",[C;3>3;][C;3>1;][->.]1[=>.][N;2>1;][O;2>1;][->...
1118,[C;D3:1]-[C;D2:2]-[N;D1:3]>>[C;D3:1]-[C;D3:2](...,2,2,"4,314",CCCCOC(=O)[C@@H]1CC[C@H](CN)CC1,1,4,[C;D2:1]-[N;D1:2]>>[C;D2:1]-[N;D2:2]=[N;D2+:4]...,n1_t4_composite_rules.tsv:0,1,p9711,[N;2>2;+](=[N;1>1;-])[.>=][N;1>1;0>-][->.][C;2...
1197,[C;D3:1]:1:[O:2]:[N;D2:3]:[C;D3:4]:2:[C;D3:5]:...,2,2,"4,314",Cc1onc2c1c(=O)n(C1CC(CN)CN(C(=O)OC(C)(C)C)C1)c...,1,4,[C;D2:1]-[N;D1:2]>>[C;D2:1]-[N;D2:2]=[N;D2+:4]...,n1_t4_composite_rules.tsv:0,1,p9712,[N;2>2;+](=[N;1>1;-])[.>=][N;1>1;0>-][->.][C;2...
...,...,...,...,...,...,...,...,...,...,...,...,...
8622,[O;D2:1]-[C;D2:2]-[N;D3:3](-[C;D3:4](=[O;D1:5]...,1,1,1837,CCOCN(C(=O)C(C)c1ccc2oc(-c3c(F)cccc3Cl)nc2c1)c...,1,4,[O;D2:1]-[C;D2:2]-[N;D3:3](-[C;D3:4](=[O:5])-[...,n1_t4_composite_rules.tsv:306,1,p9973,[Cl;1>1;][.>-][C;2>2;]([O;2>2;])[->.][N;3>1;](...
8626,[O;D2:1]-[C;D2:2]-[N;D3:3]:1:[C;D2:4]:[C:5]:[C...,1,1,1681,C[Si](C)(C)CCOCn1ccc2c(C(=NN)C3CCCCC3)ncnc21,1,4,[C:1]:[C;D3:3](:[N:2])-[C;D3:4](=[N;D2:5]-[N;D...,n1_t4_composite_rules.tsv:41,1,p9742,[O;1>1;][.>=][C;3>2;]([->.][C;3>3;]:1([.>-][I;...
8636,[O;D2:1]-[C;D2:2]-[O;D2:3]-[C;D2:4].[C;D2:5]-[...,1,1,2072,COCOCCCCCCCCCCCCCCCC=O,1,4,[C;D2:1]-[C;D2:2]=[O;D1:3]>>[C;D2:1]-[C;D2:2]-...,n1_t4_composite_rules.tsv:76,1,p9772,[O;1>1;][.>-][C;2>3;]([C;2>2;])=[O;1>1;].[Cl;1...
8708,[O;D2:1]-[N;D3:2](-[C;D2:3]-[C;D2:4])-[C;D3:5]...,1,1,2626,CON(CCCc1c(Cl)cc(Cl)cc1Cl)C(=O)c1cn(C)nc1C(F)F,1,4,[O;D2:1]-[N;D3:2](-[C;D2:3])-[C;D3:4](=[O;D1:5...,n1_t4_composite_rules.tsv:308,1,p9974,[O;1>1;][.>=][C;2>3;][->.]1([.>-][N;3>3;]([O;2...
8727,[S:1]:[C;D3:2](-[C;D3:3]-1=[N;D2:4]-[O;D2:5]-[...,1,1,960,COC(=O)c1sc(C2=NOC(c3cc(Cl)c(F)c(Cl)c3)(C(F)(F...,1,4,[C:1]:[C;D3:2](-[C;D3:3]-1=[N;D2:4]-[O;D2:5]-[...,n1_t4_composite_rules.tsv:37,1,p9738,[O;1>1;][.>=][C;4>3;][->.]1([->.][O;2>1;][N;2>...

In [28]:
y = 8252

In [29]:
alchemical_rule = smarts(df.iloc[y]['Alchemical_rule'])
alchemical_rule

In [30]:
route_id = int(df.iloc[y]['Reference'].split(',')[0])
route_id

307

In [31]:
svg = get_route_svg_from_json(routes_json, route_id, labeled=True)
display(SVG(svg))

In [32]:
comp_rules = df.iloc[y]['Composite_rules'].split(' || ')
for comp_rule in comp_rules:
    rules = comp_rule.split('$')
    for rule in rules:
        display(smarts(rule))
    print(comp_rule)

ValueError: min() arg is an empty sequence

[O;D1:1]=[C;D2:2]-[N;D2:3]-[C;D2:4]>>[O;D1:1]=[C;D2:2]-[O;D2:7]-[C;D2:6]-[C:5].[N;D1:3]-[C;D2:4]$[N;D1:1]-[C;D2:2]-[C;D2:3]>>[N;D1:1]#[C;D2:2]-[C;D2:3]$[N;D1:1]#[C;D2:2]-[C;D2:3]-[C;D3:4]>>[C;D2:3](-[C;D3:4])-[Br;D1:5].[N;D1:1]#[C;D1:2]$[Br;D1:1]-[C;D2:2]-[C;D3:3]>>[C;D2:2](-[C;D3:3])-[O;D1:4].[Br;D0:1]$[O;D1:1]-[C;D2:2]-[C;D3:3]>>[O;D1:1]=[C;D3:2](-[C;D3:3])-[O;D2:6]-[C;D2:5]-[C:4]

In [34]:
df_sorted = df.sort_values(by="composite_rules_size", ascending=False)
df_sorted

,Alchemical_rule,popularity,route_ids_size,Reference,Target_molecules,composite_rules_size,Composite_rule_sizes,Composite_rules,Source_composite_rows,pseudo_reactions_size,Pseudo_reaction_ids,Alchemical_cgr
4,[C;D2:1]-[N;D3:2](-[C;D2:3])-[C;D2:5]-[C;D2:4]...,22,22,"89,178,473,991,1159,1380,1872,1911,2102,2182,2...",CC(=O)N[C@@H]1CC[C@@H](CCN2CCC(C(=O)c3ccc(F)s3...,9,2,[C;D2:1]-[C;D2:2]-[N;D3:3](-[C;D2:4])-[C;D2:5]...,"n1_t2_composite_rules.tsv:17,n1_t2_composite_r...",18,"p236,p237,p238,p239,p240,p241,p242,p597,p598,p...",[O;1>1;][.>-][C;2>2;]([->.][N;3>2;]([C;2>2;])[...
27,[C;D3:1]-[C;D2:2]-[N;D3:3](-[C;D2:4])-[C;D2:5]...,17,17,"57,325,418,1031,1309,1960,2165,3285,3389,3542,...",CC(C)(C)OC(=O)N1CC(CN2CCC3(CC2)CCN(Cc2ccc(Br)c...,8,2,[C;D2:1]-[N;D3:2](-[C;D2:3]-[C;D3:4])-[C;D2:5]...,"n1_t2_composite_rules.tsv:199,n1_t2_composite_...",14,"p522,p523,p524,p525,p526,p980,p981,p982,p983,p...",[O;1>1;][.>-][C;2>2;]([C;3>3;])[->.][N;3>2;]([...
2,[C;D3:1]-[C;D2:2]-[C;D2:3]#[N;D1:4]>>[C;D3:1]-...,23,23,"59,218,236,449,564,811,918,966,1059,1863,1894,...","C=COCC1CCC(CC#N)CC1,CC(C)(C)[Si](OCc1cccc(CC#N...",8,2,[C;D3:1]-[C;D2:2]-[C;D2:3]#[N;D1:4]>>[C;D3:1]-...,"n1_t2_composite_rules.tsv:30,n1_t2_composite_r...",19,"p335,p337,p339,p340,p341,p517,p519,p520,p521,p...",[O;1>1;][.>-][C;2>2;]([C;3>3;])[->.][C;2>1;]#[...
8,[C;D3:1]-[C;D2:2]-[C;D2:3]#[N;D1:4]>>[C;D3:1]-...,21,21,"50,59,209,218,274,307,449,863,966,1059,1418,20...","CC(C)(C)OC(=O)N[C@H]1CCCC[C@@H]1CC#N,CC(C)(C)O...",7,2,[C;D3:1]-[C;D2:2]-[C;D2:3]#[N;D1:4]>>[C;D3:1]-...,"n1_t2_composite_rules.tsv:231,n1_t2_composite_...",15,"p336,p338,p561,p562,p563,p564,p565,p1063,p1064...",[O;1>1;][.>-][C;2>2;]([->.][C;2>1;]#[N;1>1;])[...
126,[C;D2:1]-[N;D3:2](-[C;D2:3])-[C;D2:5]-[C;D2:4]...,7,7,"51,89,473,1380,2261,4912,6798",CC(=O)N[C@@H]1CC[C@@H](CCN2CCC(C(=O)c3ccc(F)s3...,6,"2,3",[C;D2:1]-[C;D2:2]-[N;D3:3](-[C;D2:4])-[C;D2:5]...,"n1_t2_composite_rules.tsv:2311,n1_t3_composite...",7,"p3491,p8114,p8115,p8541,p8558,p8728,p8740",[O;1>1;][.>=][C;2>3;]([.>-][O;2>2;][C;2>2;][C]...
...,...,...,...,...,...,...,...,...,...,...,...,...
3070,[C;D2:1]-[C;D2:2]-[Br;D1:3]>>[Br;D1:3]-[C;D4:4...,1,1,1903,CC(=O)OCCCCCCCCCCCCCCCCCBr,1,2,[C;D2:1]-[C;D2:2]-[Br;D1:3]>>[Br;D1:3]-[C;D4:5...,n1_t2_composite_rules.tsv:2216,1,p3397,[C]1[O][C;3>3;]([O;2>2;][.>-][C;2>2;]([C;2>2;]...
3069,[C;D2:1]-[C;D2:2]-[Br;D1:3]>>[Br;D1:3]-[C;D4:4...,1,1,119,BrCCCCCOCCCCBr,1,2,[Br;D1:1]-[C;D2:2]-[C;D2:3]>>[Br;D1:1]-[C;D4:5...,n1_t2_composite_rules.tsv:771,1,p2045,[C;4>4;]([Br;1>1;])([Br;1>1;])([Br;1>1;])[.>-]...
3068,[C;D2:1]-[C;D2:2]-[Br;D1:3]>>[Br;D1:3]-[C;D4:4...,1,1,7432,CC(C)(C)OC(=O)N1CC[C@H](NC(=O)COCCBr)C1,1,2,[C;D2:1]-[C;D2:2]-[Br;D1:3]>>[Br;D1:3]-[C;D4:5...,n1_t2_composite_rules.tsv:2215,1,p3396,[C]:1:[C]([C;2>2;][O;2>2;][.>-][C;2>2;]([C;2>2...
3067,[C;D2:1]-[C;D2:2]-[Br;D1:3]>>[Br;D0:3].[C;D2:1...,1,1,1297,O=S1(=O)CCC(CCBr)CC1,1,2,[C;D2:1]-[C;D2:2]-[Br;D1:3]>>[C;D2:1]-[C;D2:2]...,n1_t2_composite_rules.tsv:2224,1,p3405,[O;1>1;][.>-][C;2>2;]([->.][Br;1>0;])[C;2>2;]
8754,[S;D4:1]-[N;D3:2](-[C;D2:3]-[C;D3:4])-[C;D2:5]...,1,1,4582,O=S1(=O)N(Cc2ccc(Br)cc2F)CCCCN1c1ccccc1,1,2,[S;D4:1]-[N;D3:2](-[C;D2:3]-[C;D3:4])-[C;D2:5]...,n1_t2_composite_rules.tsv:7113,1,p8064,[Br;1>1;][.>-][C;2>2;]([->.][N;3>3;]([.>-][C;3...

In [38]:
z = 4
df.iloc[27]

Alchemical_rule          [C;D3:1]-[C;D2:2]-[N;D3:3](-[C;D2:4])-[C;D2:5]...
popularity                                                              17
route_ids_size                                                          17
Reference                57,325,418,1031,1309,1960,2165,3285,3389,3542,...
Target_molecules         CC(C)(C)OC(=O)N1CC(CN2CCC3(CC2)CCN(Cc2ccc(Br)c...
composite_rules_size                                                     8
Composite_rule_sizes                                                     2
Composite_rules          [C;D2:1]-[N;D3:2](-[C;D2:3]-[C;D3:4])-[C;D2:5]...
Source_composite_rows    n1_t2_composite_rules.tsv:199,n1_t2_composite_...
pseudo_reactions_size                                                   14
Pseudo_reaction_ids      p522,p523,p524,p525,p526,p980,p981,p982,p983,p...
Alchemical_cgr           [O;1>1;][.>-][C;2>2;]([C;3>3;])[->.][N;3>2;]([...
Name: 27, dtype: object

In [39]:
alchemical_rule_z = smarts(df.iloc[z]['Alchemical_rule'])
alchemical_rule_z

In [41]:
comp_rules = df.iloc[z]['Composite_rules'].split(' || ')
for comp_rule in comp_rules:
    rules = comp_rule.split('$')
    for rule in rules:
        display(smarts(rule))
    # print(comp_rule)

In [4]:
from alchems.alchemical_rules.classify_alchemical import classify_alchemical_rules

In [5]:
from pathlib import Path

reference_one_step_rules_path = Path('../reference/pop_3_rules.tsv')
output = Path('../reference/')
summary_path = Path('../reference/')
summary = classify_alchemical_rules(alchemy_rules_path,
                                    reference_one_step_rules_path,
                                    output,
                                    summary_path)

In [6]:
summary

{'alchemical_rules_tsv': '../alchemical_out/n1_alchemical_rules.tsv',
 'default_rules_tsv': '../reference/pop_3_rules.tsv',
 'output': '../reference/n1_classified_alchemical_rules.tsv',
 'rows_seen': 8755,
 'positive': 8638,
 'negative': 117,
 'default_rules_parsed': 16436,
 'default_rule_parse_errors': 0,
 'alchemical_cgr_errors': 0,
 'summary_file': '../reference/n1_alchemical_rule_classification_summary.json'}

In [9]:
class_df = pd.read_csv('../reference/n1_classified_alchemical_rules.tsv', sep='\t')
class_df

,Alchemical_rule,popularity,route_ids_size,Reference,Target_molecules,composite_rules_size,Composite_rule_sizes,Composite_rules,Source_composite_rows,pseudo_reactions_size,Pseudo_reaction_ids,Alchemical_cgr,classification,Matched_default_rule_ids,Matched_default_rules
0,[C;D3:1]-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D2:5]...,26,26,"6,1168,1257,1558,1571,1587,1706,1861,2142,2398...",C=CCC(CC=C)(COc1cc(C)c(-c2ccc(C(F)(F)F)cc2)c(C...,2,2,[C;D3:1]-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D2:5]...,"n1_t2_composite_rules.tsv:0,n1_t2_composite_ru...",6,"p2,p5,p826,p827,p828,p829",[O;2>2;]([C;1>1;])[.>-][C;3>3;](=[O;1>1;])([->...,positive,NaN,NaN
1,[C;D3:1]-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D3:5]...,24,24,"37,376,494,666,707,873,1053,1127,1200,1386,174...",CC(=O)NCC(C(=O)Nc1ccccc1)c1ccc(C(=O)OC(C)(C)C)...,4,"2,3",[C;D3:1]-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D3:5]...,"n1_t2_composite_rules.tsv:1,n1_t3_composite_ru...",21,"p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p33,p3...",[O;2>2;]([C;1>1;])[.>-][C;3>3;]([C;3>3;])(=[O;...,positive,NaN,NaN
2,[C;D3:1]-[C;D2:2]-[C;D2:3]#[N;D1:4]>>[C;D3:1]-...,23,23,"59,218,236,449,564,811,918,966,1059,1863,1894,...","C=COCC1CCC(CC#N)CC1,CC(C)(C)[Si](OCc1cccc(CC#N...",8,2,[C;D3:1]-[C;D2:2]-[C;D2:3]#[N;D1:4]>>[C;D3:1]-...,"n1_t2_composite_rules.tsv:30,n1_t2_composite_r...",19,"p335,p337,p339,p340,p341,p517,p519,p520,p521,p...",[O;1>1;][.>-][C;2>2;]([C;3>3;])[->.][C;2>1;]#[...,positive,NaN,NaN
3,[C;D3:1]-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D2:5]...,23,23,"6,543,1168,1257,1571,1706,2142,2398,2839,3268,...",C=CCc1c(C(=O)NCc2c(C(C)CC=C)cc(C)nc2OC)cccc1N(...,2,"2,3",[C;D3:1]-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D2:5]...,"n1_t2_composite_rules.tsv:0,n1_t3_composite_ru...",18,"p0,p1,p6,p7,p8,p9,p10,p11,p12,p13,p14,p16,p17,...",[O;2>2;]([C;1>1;])[.>-][C;3>3;]([C;3>3;])(=[O;...,negative,125.0,[C;D3:1]-[C;D3:2](=[O;D1:5])-[N;D2:7]-[C;D2:6]...
4,[C;D2:1]-[N;D3:2](-[C;D2:3])-[C;D2:5]-[C;D2:4]...,22,22,"89,178,473,991,1159,1380,1872,1911,2102,2182,2...",CC(=O)N[C@@H]1CC[C@@H](CCN2CCC(C(=O)c3ccc(F)s3...,9,2,[C;D2:1]-[C;D2:2]-[N;D3:3](-[C;D2:4])-[C;D2:5]...,"n1_t2_composite_rules.tsv:17,n1_t2_composite_r...",18,"p236,p237,p238,p239,p240,p241,p242,p597,p598,p...",[O;1>1;][.>-][C;2>2;]([->.][N;3>2;]([C;2>2;])[...,positive,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8750,[S;D4:1]-[C;D3:2]:1:[N;D2:3]:[N;D2:4]:[C;D3:5]...,1,1,1190,O=S(=O)(c1ccccc1)c1n[nH]c2ccc(OCCNC3CC3)cc12,1,3,[C;D2:1]-[C;D2:2]-[N;D2:3]-[C;D3:4]>>[C;D2:1]-...,n1_t3_composite_rules.tsv:462,1,p8529,[O;2>2;]([S;4>4;]([C]:1:[C]:[C]:[C]([C]):[C]:[...,positive,NaN,NaN
8751,[S;D4:1]-[C;D3:2]:1:[N;D2:3]:[N;D2:4]:[C;D3:5]...,1,1,2210,O=S(=O)(c1cccc2ccccc12)c1n[nH]c2c(OC(CCl)CCl)c...,1,2,[S;D4:1]-[C;D3:2]:1:[N;D2:3]:[N;D2:4]:[C;D3:5]...,n1_t2_composite_rules.tsv:7103,1,p8054,[O;1>1;][.>-][N;2>2;][:>.]1([.>=][O;1>1;])[:>....,positive,NaN,NaN
8752,[S;D4:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[N;D2:5]...,1,1,1013,COCCc1sc(S(=O)(=O)NC(=O)Nc2cc(SC)cc(NCCF)n2)cc1C,1,2,[S;D4:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[N;D2:5]...,n1_t2_composite_rules.tsv:7104,1,p8055,[Cl;1>1;][.>-][C;3>3;]([.>-][O;2>2;][C;3>3;]:1...,positive,NaN,NaN
8753,[S;D4:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[N;D2:5]...,1,1,4006,C[Se]c1ccccc1S(=O)(=O)NC(=O)Nc1nc(C)cc(C)n1,1,2,[S;D4:1]-[N;D2:2]-[C;D3:3](=[O;D1:4])-[N;D2:5]...,n1_t2_composite_rules.tsv:7105,1,p8056,[C;2>2;][.>-]1[.>-][C;3>2;][:>.]2([N;2>2;][->=...,positive,NaN,NaN
8754,[S;D4:1]-[N;D3:2](-[C;D2:3]-[C;D3:4])-[C;D2:5]...,1,1,4582,O=S1(=O)N(Cc2ccc(Br)cc2F)CCCCN1c1ccccc1,1,2,[S;D4:1]-[N;D3:2](-[C;D2:3]-[C;D3:4])-[C;D2:5]...,n1_t2_composite_rules.tsv:7113,1,p8064,[Br;1>1;][.>-][C;2>2;]([->.][N;3>3;]([.>-][C;3...,positive,NaN,NaN

In [13]:
val = 'negative'
rows_with_val = class_df[
    class_df["classification"] == val
]
rows_with_val

,Alchemical_rule,popularity,route_ids_size,Reference,Target_molecules,composite_rules_size,Composite_rule_sizes,Composite_rules,Source_composite_rows,pseudo_reactions_size,Pseudo_reaction_ids,Alchemical_cgr,classification,Matched_default_rule_ids,Matched_default_rules
3,[C;D3:1]-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D2:5]...,23,23,"6,543,1168,1257,1571,1706,2142,2398,2839,3268,...",C=CCc1c(C(=O)NCc2c(C(C)CC=C)cc(C)nc2OC)cccc1N(...,2,"2,3",[C;D3:1]-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D2:5]...,"n1_t2_composite_rules.tsv:0,n1_t3_composite_ru...",18,"p0,p1,p6,p7,p8,p9,p10,p11,p12,p13,p14,p16,p17,...",[O;2>2;]([C;1>1;])[.>-][C;3>3;]([C;3>3;])(=[O;...,negative,125.0,[C;D3:1]-[C;D3:2](=[O;D1:5])-[N;D2:7]-[C;D2:6]...
10,[C;D3:1]-[C;D2:2]-[N;D2:3]=[N;D2+:4]>>[C;D3:1]...,20,20,"4,44,151,314,322,489,492,1051,1077,1148,1669,2...",C=C1[C@@H](OC(C)=O)C[C@H]2[C@H](CN=[N+]=[N-])[...,3,2,[C;D3:1]-[C;D2:2]-[N;D2:3]=[N;D2+:4]>>[C;D3:1]...,"n1_t2_composite_rules.tsv:10,n1_t2_composite_r...",15,"p168,p169,p172,p173,p175,p176,p177,p178,p179,p...",[O;1>1;][.>-][C;2>2;]([C;3>3;])[->.][N;2>1;0>-...,negative,859.0,[C;D3:1]-[C;D2:2]-[N;D2:3]=[N;D2+:4]>>[C;D3:1]...
27,[C;D3:1]-[C;D2:2]-[N;D3:3](-[C;D2:4])-[C;D2:5]...,17,17,"57,325,418,1031,1309,1960,2165,3285,3389,3542,...",CC(C)(C)OC(=O)N1CC(CN2CCC3(CC2)CCN(Cc2ccc(Br)c...,8,2,[C;D2:1]-[N;D3:2](-[C;D2:3]-[C;D3:4])-[C;D2:5]...,"n1_t2_composite_rules.tsv:199,n1_t2_composite_...",14,"p522,p523,p524,p525,p526,p980,p981,p982,p983,p...",[O;1>1;][.>-][C;2>2;]([C;3>3;])[->.][N;3>2;]([...,negative,309.0,[C;D3:1]-[C;D2:2]-[N;D3:5](-[C;D2:4])-[C;D2:6]...
44,[C;D3:1]-[O;D2:2]-[C;D2:3]-[C;D2:4]>>[C;D2:3](...,13,13,"95,575,643,714,718,819,1881,2139,2160,3598,448...",CCCOc1nc(Cc2ccc(Cl)cc2)nc2oc(-c3cc(C)c(OCCCBr)...,1,2,[C;D3:1]-[O;D2:2]-[C;D2:3]-[C;D2:4]>>[C;D2:3](...,n1_t2_composite_rules.tsv:8,6,"p144,p147,p151,p152,p154,p155",[C;1>1;][.>-][O;2>2;]([C;3>3;])[->.][C;2>2;]([...,negative,5051.0,[C;D3:1]-[O;D2:2]-[C;D2:5]-[C;D2:6]>>[C;D3:1]-...
61,[C;D3:1]-[C;D2:2]-[O;D2:3]-[C;D3:4]>>[C;D3:1]-...,10,10,"42,294,433,674,1048,1094,1470,2724,5157,7298","COC(=O)C(C)Oc1ccc(COc2ccc(Cl)cc2)cc1,COc1cc(CO...",6,2,[C;D3:1]-[C;D2:2]-[O;D2:3]-[C;D3:4]>>[C;D3:1]-...,"n1_t2_composite_rules.tsv:201,n1_t2_composite_...",8,"p985,p986,p987,p1616,p1618,p5116,p5117,p6071",[O;1>1;][.>-][C;2>2;]([C;3>3;])[->.][O;2>1;][C...,negative,39.0,[C;D2:1](-[C;D3:3])-[O;D2:4]-[C;D3:5]>>[O;D1:4...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6902,[C;D4:1]-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D2:5]...,1,1,7053,CC(C)(C)OC(=O)N1CCC(Cc2ccc(-c3ccccc3)cc2)(C(=O...,1,2,[C;D4:1]-[C;D3:2](=[O;D1:3])-[N;D2:4]-[C;D2:5]...,n1_t2_composite_rules.tsv:5549,1,p6601,[O;2>2;]([C;1>1;])[.>-][C;3>3;]([C;4>4;])(=[O;...,negative,4423.0,[C;D4:1]-[C;D3:2](=[O;D1:3])-[N;D2:5]-[C;D2:4]...
6921,[C;D4:1]-[C;D3:2](=[O;D1:3])-[N;D3:4](-[C;D2:5...,1,1,808,CC(C)(Sc1ccc2nc(N)sc2c1)C(=O)N1CCCC1,1,2,[C;D4:1]-[C;D3:2](=[O;D1:3])-[N;D3:4](-[C;D2:5...,n1_t2_composite_rules.tsv:5567,1,p6619,[O;2>2;]([C;2>2;][C])[.>-][C;3>3;]([C;4>4;])(=...,negative,6502.0,[C;D4:1]-[C;D3:2](=[O;D1:6])-[N;D3:7](-[C;D2:8...
6986,[C;D4:1]-[S;D4:2](=[O;D1:3])(=[O;D1:4])-[N;D2:...,1,1,8511,C=CCC1(S(=O)(=O)Nc2ccc(F)c(F)c2Nc2ccc(I)cc2F)CC1,1,2,[C;D4:1]-[S;D4:2](=[O;D1:3])(=[O;D1:4])-[N;D2:...,n1_t2_composite_rules.tsv:5620,1,p6672,[O;1>1;][.>-][S;4>4;]([C;4>4;])(=[O;1>1;])(=[O...,negative,11590.0,[C;D4:1]-[S;D4:2](=[O;D1:4])(=[O;D1:5])-[N;D2:...
7736,[N;D3:1]-[C;D3:2]:1:[C;D2:3]:[C;D3:4](-[C;D1:5...,1,1,9118,COC(=O)[C@@H]1C[C@@H](S(C)(=O)=O)CN1c1cc(C)nn1...,1,2,[N;D3:1]-[C;D3:2]:1:[C;D2:3]:[C;D3:4](-[C;D1:5...,n1_t2_composite_rules.tsv:6383,1,p7360,[O;1>1;][.>=][C;3>3;][:>.]1([N;3>3;])[:>-][C;2...,negative,15560.0,[N;D3:1]-[C;D3:2]:1:[C;D2:3]:[C;D3:4](-[C;D1:5...
8684,[O;D2:1]-[N;D2:2]-[C;D2:3]-[C;D2:4]>>[O;D2:1]-...,1,1,2626,CONCCCc1c(Cl)cc(Cl)cc1Cl,1,2,[O;D2:1]-[N;D2:2]-[C;D2:3]-[C;D2:4]>>[O;D2:1]-...,n1_t2_composite_rules.tsv:7042,1,p7995,[O;1>1;][.>=][C;2>2;]([->.][N;2>1;][O;2>2;])[C...,negative,11432.0,[O;D2:1]-[N;D2:2]-[C;D2:4]-[C;D2:3]>>[C;D2:3]-...

In [23]:
neg_num = 61

smarts(df.iloc[neg_num]['Alchemical_rule'])